#ifndef LOS_MEMORY_MANAGER_SERVICE_MAIN_INTERNAL_H
#define LOS_MEMORY_MANAGER_SERVICE_MAIN_INTERNAL_H

#include "MemoryManagerAddressSpace.h"

#define LOS_MEMORY_MANAGER_SERVICE_SERIAL_COM1_BASE 0x3F8U

#define LOS_MEMORY_MANAGER_ATTACH_STAGE_NONE 0ULL
#define LOS_MEMORY_MANAGER_ATTACH_STAGE_LAUNCH_BLOCK 1ULL
#define LOS_MEMORY_MANAGER_ATTACH_STAGE_DIRECT_MAP_OFFSET 2ULL
#define LOS_MEMORY_MANAGER_ATTACH_STAGE_TASK_OBJECT_TRANSLATION 3ULL
#define LOS_MEMORY_MANAGER_ATTACH_STAGE_RECEIVE_ENDPOINT 4ULL
#define LOS_MEMORY_MANAGER_ATTACH_STAGE_REPLY_ENDPOINT 5ULL
#define LOS_MEMORY_MANAGER_ATTACH_STAGE_EVENT_ENDPOINT 6ULL
#define LOS_MEMORY_MANAGER_ATTACH_STAGE_ADDRESS_SPACE_OBJECT 7ULL
#define LOS_MEMORY_MANAGER_ATTACH_STAGE_TASK_OBJECT 8ULL
#define LOS_MEMORY_MANAGER_ATTACH_STAGE_MEMORY_VIEW 9ULL
#define LOS_MEMORY_MANAGER_ATTACH_STAGE_HEAP 10ULL

#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_NONE 0ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_NULL 1ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_SIGNATURE 2ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_VERSION 3ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_ENDPOINT_ID 4ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_ROLE 5ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_MAILBOX_PHYSICAL 6ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_MAILBOX_FLAG 7ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_STATE 8ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_SERVICE_IMAGE_PHYSICAL 9ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_ROOT_TABLE_PHYSICAL 10ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_KERNEL_ROOT_PHYSICAL 11ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_ADDRESS_SPACE_OBJECT_PHYSICAL 12ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_ENTRY_VIRTUAL 13ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_STACK_TOP_PHYSICAL 14ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_STACK_TOP_VIRTUAL 15ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_LAUNCH_BLOCK_PHYSICAL 16ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_REQUEST_MAILBOX_PHYSICAL 17ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_RESPONSE_MAILBOX_PHYSICAL 18ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_EVENT_MAILBOX_PHYSICAL 19ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_RECEIVE_ENDPOINT_PHYSICAL 20ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_REPLY_ENDPOINT_PHYSICAL 21ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_EVENT_ENDPOINT_PHYSICAL 22ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_ADDRESS_SPACE_OBJECT_PHYSICAL_POINTER 23ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_TASK_OBJECT_PHYSICAL_POINTER 24ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_SERVICE_ROOT_PHYSICAL 25ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_MEMORY_REGION_TABLE_PHYSICAL 26ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_MEMORY_REGION_COUNT 27ULL
#define LOS_MEMORY_MANAGER_ATTACH_DETAIL_MEMORY_REGION_ENTRY_SIZE 28ULL

extern volatile UINT64 LosMemoryManagerServiceHeartbeat;
extern const char LosMemoryManagerServiceBanner[];

void LosMemoryManagerRecordAttachDiagnostic(LOS_MEMORY_MANAGER_TASK_OBJECT *TaskObject, UINT64 Stage, UINT64 Detail);
void LosMemoryManagerServiceSerialInit(void);
void LosMemoryManagerServiceSerialWriteChar(char Character);
void LosMemoryManagerServiceSerialWriteText(const char *Text);
void LosMemoryManagerServiceSerialWriteHex64(UINT64 Value);
void LosMemoryManagerServiceSerialWriteLine(const char *Text);
void LosMemoryManagerServiceSerialWriteUnsigned(UINT64 Value);
void LosMemoryManagerServiceSerialWriteNamedHex(const char *Name, UINT64 Value);
void LosMemoryManagerServiceSerialWriteNamedUnsigned(const char *Name, UINT64 Value);
void LosMemoryManagerHardFail(const char *RuleName, UINT64 Value0, UINT64 Value1, UINT64 Value2);
const char *LosMemoryManagerBootstrapAttachResultName(UINT32 BootstrapResult);
void LosMemoryManagerZeroMemory(void *Buffer, UINTN ByteCount);
void LosMemoryManagerCopyBytes(void *Destination, const void *Source, UINTN ByteCount);
UINT64 LosMemoryManagerResolveDirectMapOffset(const LOS_MEMORY_MANAGER_LAUNCH_BLOCK *LaunchBlock, UINT64 LaunchBlockAddress);
void *LosMemoryManagerTranslateBootstrapAddress(UINT64 DirectMapOffset, UINT64 PhysicalAddress);
void LosMemoryManagerRecordEntryBreadcrumbFromLaunchBlock(UINT64 LaunchBlockAddress, UINT64 Stage, UINT64 Value);
BOOLEAN LosMemoryManagerValidateEndpointObjectDetailed(
    const LOS_MEMORY_MANAGER_ENDPOINT_OBJECT *Endpoint,
    UINT64 EndpointId,
    UINT32 Role,
    UINT64 MailboxPhysicalAddress,
    UINT64 *Detail);
BOOLEAN LosMemoryManagerValidateAddressSpaceObjectDetailed(
    const LOS_MEMORY_MANAGER_ADDRESS_SPACE_OBJECT *AddressSpaceObject,
    UINT64 ServiceImagePhysicalAddress,
    UINT64 ServiceRootTablePhysicalAddress,
    UINT64 *Detail);
BOOLEAN LosMemoryManagerValidateTaskObjectDetailed(
    const LOS_MEMORY_MANAGER_TASK_OBJECT *TaskObject,
    UINT64 AddressSpaceObjectPhysicalAddress,
    UINT64 EntryVirtualAddress,
    UINT64 StackTopPhysicalAddress,
    UINT64 StackTopVirtualAddress,
    UINT64 *Detail);
BOOLEAN LosMemoryManagerValidateLaunchBlockDetailed(const LOS_MEMORY_MANAGER_LAUNCH_BLOCK *LaunchBlock, UINT64 *Detail);
void LosMemoryManagerInitializeServiceResponse(
    const LOS_MEMORY_MANAGER_REQUEST_MESSAGE *Request,
    LOS_MEMORY_MANAGER_RESPONSE_MESSAGE *Response);
BOOLEAN LosMemoryManagerServiceMayHandleOperation(const LOS_MEMORY_MANAGER_SERVICE_STATE *State, UINT32 Operation);
BOOLEAN LosMemoryManagerCompleteRequest(
    LOS_MEMORY_MANAGER_SERVICE_STATE *State,
    const LOS_MEMORY_MANAGER_RESPONSE_MESSAGE *Response);
UINT32 LosMemoryManagerBootstrapAttachStatusFromResult(UINT32 BootstrapResult);
UINT32 LosMemoryManagerValidateBootstrapAttachRequest(
    const LOS_MEMORY_MANAGER_SERVICE_STATE *State,
    const LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_REQUEST *Request);
void LosMemoryManagerPopulateBootstrapAttachResponse(
    LOS_MEMORY_MANAGER_SERVICE_STATE *State,
    const LOS_MEMORY_MANAGER_REQUEST_MESSAGE *Request,
    LOS_MEMORY_MANAGER_RESPONSE_MESSAGE *Response);
void LosMemoryManagerPostEvent(UINT32 EventType, UINT32 Status, UINT64 Value0, UINT64 Value1);
void LosMemoryManagerRunServiceStep(void);

#endif
