/*
 * File Name: MemoryManagerMain.h
 * File Version: 0.3.25
 * Author: OpenAI
 * Email: dave66samaa@gmail.com
 * Creation Timestamp: 2026-04-07T07:24:34Z
 * Last Update Timestamp: 2026-04-08T12:10:00Z
 * Operating System Name: Liberation OS
 * Purpose: Implements a Liberation OS service component.
 */

#ifndef LOS_MEMORY_MANAGER_SERVICE_MAIN_H
#define LOS_MEMORY_MANAGER_SERVICE_MAIN_H

#include "Efi.h"
#include "MemoryManagerServiceAbi.h"
#include "CapabilitiesServiceAbi.h"
#include "MemoryManagerHeap.h"

#define LOS_MEMORY_MANAGER_MAX_INTERNAL_MEMORY_DESCRIPTORS 8192U
#define LOS_MEMORY_MANAGER_MAX_PAGE_FRAME_DATABASE_ENTRIES 8192U

#define LOS_MEMORY_MANAGER_MEMORY_CATEGORY_USABLE 1U
#define LOS_MEMORY_MANAGER_MEMORY_CATEGORY_BOOTSTRAP_RESERVED 2U
#define LOS_MEMORY_MANAGER_MEMORY_CATEGORY_FIRMWARE_RESERVED 3U
#define LOS_MEMORY_MANAGER_MEMORY_CATEGORY_RUNTIME 4U
#define LOS_MEMORY_MANAGER_MEMORY_CATEGORY_MMIO 5U
#define LOS_MEMORY_MANAGER_MEMORY_CATEGORY_ACPI_NVS 6U
#define LOS_MEMORY_MANAGER_MEMORY_CATEGORY_UNUSABLE 7U

#define LOS_MEMORY_MANAGER_PAGE_FRAME_STATE_FREE 1U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_STATE_RESERVED 2U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_STATE_RUNTIME 3U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_STATE_MMIO 4U

#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_FREE 0U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_BOOTSTRAP_RESERVED 1U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_FIRMWARE_RESERVED 2U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_RUNTIME 3U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_MMIO 4U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_ACPI_NVS 5U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_UNUSABLE 6U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_SERVICE_IMAGE 7U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_SERVICE_STACK 8U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_REQUEST_MAILBOX 9U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_RESPONSE_MAILBOX 10U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_EVENT_MAILBOX 11U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_LAUNCH_BLOCK 12U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_ENDPOINT_OBJECT 13U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_ADDRESS_SPACE_OBJECT 14U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_TASK_OBJECT 15U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_PAGE_TABLE 16U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_DYNAMIC_RESERVED 17U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_DYNAMIC_CLAIMED 18U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_HEAP_METADATA 19U
#define LOS_MEMORY_MANAGER_PAGE_FRAME_USAGE_HEAP_INTERNAL 20U

#define LOS_MEMORY_MANAGER_MEMORY_VIEW_DETAIL_NONE 0ULL
#define LOS_MEMORY_MANAGER_MEMORY_VIEW_DETAIL_TABLE_PHYSICAL 1ULL
#define LOS_MEMORY_MANAGER_MEMORY_VIEW_DETAIL_TABLE_COUNT 2ULL
#define LOS_MEMORY_MANAGER_MEMORY_VIEW_DETAIL_TABLE_ENTRY_SIZE 3ULL
#define LOS_MEMORY_MANAGER_MEMORY_VIEW_DETAIL_TABLE_TRANSLATION 4ULL
#define LOS_MEMORY_MANAGER_MEMORY_VIEW_DETAIL_DESCRIPTOR_CAPACITY 5ULL
#define LOS_MEMORY_MANAGER_MEMORY_VIEW_DETAIL_FRAME_DATABASE_CAPACITY 6ULL
#define LOS_MEMORY_MANAGER_MEMORY_VIEW_DETAIL_OVERLAY_CONFLICT 7ULL
#define LOS_MEMORY_MANAGER_MEMORY_VIEW_DETAIL_RANGE_INVALID 8ULL

typedef struct
{
    UINT64 Base;
    UINT64 Length;
    UINT32 Category;
    UINT32 Flags;
    UINT32 Owner;
    UINT32 Source;
} LOS_MEMORY_MANAGER_INTERNAL_MEMORY_DESCRIPTOR;

typedef struct
{
    UINT64 BaseAddress;
    UINT64 PageCount;
    UINT32 State;
    UINT32 Usage;
    UINT32 Owner;
    UINT32 Source;
    UINT64 Attributes;
} LOS_MEMORY_MANAGER_PAGE_FRAME_DATABASE_ENTRY;

typedef struct
{
    const LOS_X64_MEMORY_REGION *NormalizedRegionTable;
    UINT64 NormalizedRegionTablePhysicalAddress;
    UINT64 NormalizedRegionCount;
    UINT64 NormalizedRegionEntrySize;
    UINT64 TotalUsableBytes;
    UINT64 TotalBootstrapReservedBytes;
    UINT64 TotalFirmwareReservedBytes;
    UINT64 TotalRuntimeBytes;
    UINT64 TotalMmioBytes;
    UINT64 TotalAcpiBytes;
    UINT64 TotalUnusableBytes;
    UINT64 TotalPages;
    UINT64 FreePages;
    UINT64 ReservedPages;
    UINT64 RuntimePages;
    UINT64 MmioPages;
    UINTN InternalDescriptorCount;
    UINTN PageFrameDatabaseEntryCount;
    UINTN BaselinePageFrameDatabaseEntryCount;
    UINTN DynamicAllocationCount;
    UINT32 Ready;
    UINT32 Reserved0;
    UINT64 AllocationGeneration;
    LOS_MEMORY_MANAGER_INTERNAL_MEMORY_DESCRIPTOR InternalDescriptors[LOS_MEMORY_MANAGER_MAX_INTERNAL_MEMORY_DESCRIPTORS];
    LOS_MEMORY_MANAGER_PAGE_FRAME_DATABASE_ENTRY PageFrameDatabase[LOS_MEMORY_MANAGER_MAX_PAGE_FRAME_DATABASE_ENTRIES];
    LOS_MEMORY_MANAGER_PAGE_FRAME_DATABASE_ENTRY BaselinePageFrameDatabase[LOS_MEMORY_MANAGER_MAX_PAGE_FRAME_DATABASE_ENTRIES];
    LOS_MEMORY_MANAGER_PAGE_FRAME_DATABASE_ENTRY DynamicAllocations[LOS_MEMORY_MANAGER_MAX_PAGE_FRAME_DATABASE_ENTRIES];
} LOS_MEMORY_MANAGER_MEMORY_VIEW;

typedef struct LOS_MEMORY_MANAGER_SERVICE_STATE
{
    LOS_MEMORY_MANAGER_LAUNCH_BLOCK *LaunchBlock;
    LOS_MEMORY_MANAGER_ENDPOINT_OBJECT *ReceiveEndpoint;
    LOS_MEMORY_MANAGER_ENDPOINT_OBJECT *ReplyEndpoint;
    LOS_MEMORY_MANAGER_ENDPOINT_OBJECT *EventEndpoint;
    LOS_MEMORY_MANAGER_REQUEST_MAILBOX *RequestMailbox;
    LOS_MEMORY_MANAGER_RESPONSE_MAILBOX *ResponseMailbox;
    LOS_MEMORY_MANAGER_EVENT_MAILBOX *EventMailbox;
    LOS_MEMORY_MANAGER_ADDRESS_SPACE_OBJECT *AddressSpaceObject;
    LOS_MEMORY_MANAGER_TASK_OBJECT *TaskObject;
    UINT64 Heartbeat;
    UINT64 LastRequestId;
    UINT64 DirectMapOffset;
    UINT64 ActiveRootTablePhysicalAddress;
    UINT64 KernelRootTablePhysicalAddress;
    UINT64 NegotiatedOperations;
    UINT32 Online;
    UINT32 AttachComplete;
    UINT32 BootstrapResultCode;
    UINT32 Reserved0;
    UINT64 NextAddressSpaceId;
    LOS_MEMORY_MANAGER_HEAP_STATE Heap;
    LOS_MEMORY_MANAGER_MEMORY_VIEW MemoryView;
} LOS_MEMORY_MANAGER_SERVICE_STATE;

void LosMemoryManagerServiceEntry(void);
void LosMemoryManagerServiceBootstrapEntry(UINT64 LaunchBlockAddress);
BOOLEAN LosMemoryManagerServiceAttach(const LOS_MEMORY_MANAGER_LAUNCH_BLOCK *LaunchBlock);
void LosMemoryManagerServicePoll(void);
LOS_MEMORY_MANAGER_SERVICE_STATE *LosMemoryManagerServiceState(void);
BOOLEAN LosMemoryManagerServiceBuildMemoryView(LOS_MEMORY_MANAGER_SERVICE_STATE *State, UINT64 *Detail);
void LosMemoryManagerServiceQueryMemoryRegions(LOS_MEMORY_MANAGER_SERVICE_STATE *State, const LOS_MEMORY_MANAGER_REQUEST_MESSAGE *Request, LOS_MEMORY_MANAGER_RESPONSE_MESSAGE *Response);
void LosMemoryManagerServiceAllocateFrames(LOS_MEMORY_MANAGER_SERVICE_STATE *State, const LOS_MEMORY_MANAGER_ALLOCATE_FRAMES_REQUEST *Request, LOS_MEMORY_MANAGER_ALLOCATE_FRAMES_RESULT *Result);
void LosMemoryManagerServiceReserveFrames(LOS_MEMORY_MANAGER_SERVICE_STATE *State, const LOS_X64_RESERVE_FRAMES_REQUEST *Request, LOS_X64_RESERVE_FRAMES_RESULT *Result);
void LosMemoryManagerServiceClaimFrames(LOS_MEMORY_MANAGER_SERVICE_STATE *State, const LOS_X64_CLAIM_FRAMES_REQUEST *Request, LOS_X64_CLAIM_FRAMES_RESULT *Result);
void LosMemoryManagerServiceFreeFrames(LOS_MEMORY_MANAGER_SERVICE_STATE *State, const LOS_X64_FREE_FRAMES_REQUEST *Request, LOS_X64_FREE_FRAMES_RESULT *Result);
BOOLEAN LosMemoryManagerServiceClaimTrackedFrames(
    LOS_MEMORY_MANAGER_SERVICE_STATE *State,
    UINT64 PageCount,
    UINT64 AlignmentBytes,
    UINT32 Flags,
    UINT32 Owner,
    UINT32 Usage,
    UINT64 *BaseAddress);
BOOLEAN LosMemoryManagerServiceFreeTrackedFrames(LOS_MEMORY_MANAGER_SERVICE_STATE *State, UINT64 PhysicalAddress, UINT64 PageCount);
BOOLEAN LosMemoryManagerServiceAuthorizeRequest(const LOS_MEMORY_MANAGER_REQUEST_MESSAGE *Request,
                                               const char *Namespace,
                                               const char *Name,
                                               UINT64 *MatchingGrantId);
void LosMemoryManagerPopulateAccessDeniedResponse(UINT32 Operation, LOS_MEMORY_MANAGER_RESPONSE_MESSAGE *Response);
UINT32 LosCapabilitiesServiceSubmitAccessRequest(const LOS_CAPABILITIES_ACCESS_REQUEST *Request,
                                                  LOS_CAPABILITIES_ACCESS_RESULT *Result);

#endif
