#ifndef LOS_MEMORY_MANAGER_ADDRESS_SPACE_H
#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_H

#include "MemoryManagerMain.h"

void LosMemoryManagerServiceCreateAddressSpace(
    LOS_MEMORY_MANAGER_SERVICE_STATE *State,
    const LOS_MEMORY_MANAGER_CREATE_ADDRESS_SPACE_REQUEST *Request,
    LOS_MEMORY_MANAGER_CREATE_ADDRESS_SPACE_RESULT *Result);
void LosMemoryManagerServiceDestroyAddressSpace(
    LOS_MEMORY_MANAGER_SERVICE_STATE *State,
    const LOS_MEMORY_MANAGER_DESTROY_ADDRESS_SPACE_REQUEST *Request,
    LOS_MEMORY_MANAGER_DESTROY_ADDRESS_SPACE_RESULT *Result);
void LosMemoryManagerServiceAttachStagedImage(
    LOS_MEMORY_MANAGER_SERVICE_STATE *State,
    const LOS_MEMORY_MANAGER_ATTACH_STAGED_IMAGE_REQUEST *Request,
    LOS_MEMORY_MANAGER_ATTACH_STAGED_IMAGE_RESULT *Result);
void LosMemoryManagerServiceAllocateAddressSpaceStack(
    LOS_MEMORY_MANAGER_SERVICE_STATE *State,
    const LOS_MEMORY_MANAGER_ALLOCATE_ADDRESS_SPACE_STACK_REQUEST *Request,
    LOS_MEMORY_MANAGER_ALLOCATE_ADDRESS_SPACE_STACK_RESULT *Result);

#endif
