/*
 * File Name: MemoryManagerServiceAbiSection01.h
 * File Version: 0.0.1
 * Author: OpenAI
 * Email: dave66samaa@gmail.com
 * Creation Timestamp: 2026-04-09T19:40:00Z
 * Last Update Timestamp: 2026-04-09T19:40:00Z
 * Operating System Name: Liberation OS
 * Purpose: Contains a split section extracted from MemoryManagerServiceAbi.h.
 */

#include "Efi.h"
#include "VirtualMemory.h"
#include "CapabilitiesServiceAbi.h"

#define LOS_MEMORY_MANAGER_BOOTSTRAP_VERSION 12U
#define LOS_MEMORY_MANAGER_SERVICE_PATH_CHARACTERS 128U
#define LOS_MEMORY_MANAGER_SERVICE_NAME "MemoryManager"

#define LOS_MEMORY_MANAGER_ENDPOINT_KERNEL_TO_SERVICE 0x4D4D535256000001ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_SERVICE_TO_KERNEL 0x4D4D535256000002ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_SERVICE_EVENTS 0x4D4D535256000003ULL

#define LOS_MEMORY_MANAGER_ENDPOINT_ROLE_RECEIVE 1U
#define LOS_MEMORY_MANAGER_ENDPOINT_ROLE_REPLY 2U
#define LOS_MEMORY_MANAGER_ENDPOINT_ROLE_EVENT 3U

#define LOS_MEMORY_MANAGER_ENDPOINT_STATE_OFFLINE 0U
#define LOS_MEMORY_MANAGER_ENDPOINT_STATE_DEFINED 1U
#define LOS_MEMORY_MANAGER_ENDPOINT_STATE_READY 2U
#define LOS_MEMORY_MANAGER_ENDPOINT_STATE_BOUND 3U
#define LOS_MEMORY_MANAGER_ENDPOINT_STATE_ONLINE 4U

#define LOS_MEMORY_MANAGER_ENDPOINT_FLAG_KERNEL_OWNED 0x0000000000000001ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_FLAG_BOOTSTRAP_OBJECT 0x0000000000000002ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_FLAG_MAILBOX_ATTACHED 0x0000000000000004ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_FLAG_SERVICE_VISIBLE 0x0000000000000008ULL

#define LOS_MEMORY_MANAGER_OPERATION_BOOTSTRAP_ATTACH 1U
#define LOS_MEMORY_MANAGER_OPERATION_ALLOCATE_FRAMES 2U
#define LOS_MEMORY_MANAGER_OPERATION_FREE_FRAMES 3U
#define LOS_MEMORY_MANAGER_OPERATION_CREATE_ADDRESS_SPACE 4U
#define LOS_MEMORY_MANAGER_OPERATION_DESTROY_ADDRESS_SPACE 5U
#define LOS_MEMORY_MANAGER_OPERATION_MAP_PAGES 6U
#define LOS_MEMORY_MANAGER_OPERATION_UNMAP_PAGES 7U
#define LOS_MEMORY_MANAGER_OPERATION_PROTECT_PAGES 8U
#define LOS_MEMORY_MANAGER_OPERATION_QUERY_MAPPING 9U

#define LOS_MEMORY_MANAGER_OPERATION_ATTACH_STAGED_IMAGE 10U
#define LOS_MEMORY_MANAGER_OPERATION_ALLOCATE_ADDRESS_SPACE_STACK 11U
#define LOS_MEMORY_MANAGER_OPERATION_QUERY_MEMORY_REGIONS 12U
#define LOS_MEMORY_MANAGER_OPERATION_RESERVE_FRAMES 13U
#define LOS_MEMORY_MANAGER_OPERATION_CLAIM_FRAMES 14U

#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_READY 0U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_ALREADY_ATTACHED 1U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_INVALID_REQUEST 2U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_VERSION_MISMATCH 3U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_LAUNCH_BLOCK_MISMATCH 4U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_ENDPOINT_MISMATCH 5U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_MAILBOX_MISMATCH 6U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_SERVICE_ROOT_MISMATCH 7U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_SERVICE_IMAGE_MISMATCH 8U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_SERVICE_STATE_INVALID 9U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_OPERATION_SET_INVALID 10U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_ENTRY_MISMATCH 11U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_STACK_TOP_MISMATCH 12U

#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_OFFLINE 0U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_DEFINED 1U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_LAUNCHED 2U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_STAGED 3U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_IMAGE_READY 4U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_READY 5U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_SERVICE_PREPARED 6U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_SERVICE_ONLINE 7U

#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_KERNEL_LOW_LEVEL_FRAMES 0x0000000000000001ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_KERNEL_LOW_LEVEL_PAGING 0x0000000000000002ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_ENDPOINT_BRIDGE 0x0000000000000004ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_PROBE_COMPLETE 0x0000000000000008ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_TRANSPORT_READY 0x0000000000000010ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_LAUNCH_BLOCK_READY 0x0000000000000020ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_STACK_READY 0x0000000000000040ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_IMAGE_READY 0x0000000000000080ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_ENTRY_PUBLISHED 0x0000000000000100ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_LAUNCH_PREPARED 0x0000000000000200ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_ONLINE 0x0000000000000400ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_ISOLATED_ROOT_READY 0x0000000000000800ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_CONTEXT_SWITCHED 0x0000000000001000ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_ATTACH_COMPLETE 0x0000000000008000ULL

#define LOS_MEMORY_MANAGER_ENDPOINT_OBJECT_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_OBJECT_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_TASK_OBJECT_PAGE_COUNT 1U

#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_STATE_OFFLINE 0U
#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_STATE_DEFINED 1U
#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_STATE_READY 2U
#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_STATE_ACTIVE 3U

#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_FLAG_HAS_IMAGE 0x0000000000000010ULL
#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_FLAG_HAS_STACK 0x0000000000000020ULL

#define LOS_MEMORY_MANAGER_RESERVED_VIRTUAL_REGION_TYPE_IMAGE 1U
#define LOS_MEMORY_MANAGER_RESERVED_VIRTUAL_REGION_TYPE_STACK 2U
#define LOS_MEMORY_MANAGER_MAX_RESERVED_VIRTUAL_REGIONS 32U

#define LOS_MEMORY_MANAGER_TASK_STATE_OFFLINE 0U
#define LOS_MEMORY_MANAGER_TASK_STATE_DEFINED 1U
#define LOS_MEMORY_MANAGER_TASK_STATE_READY 2U
#define LOS_MEMORY_MANAGER_TASK_STATE_LAUNCHED 3U
#define LOS_MEMORY_MANAGER_TASK_STATE_RUNNING 4U
#define LOS_MEMORY_MANAGER_TASK_STATE_ONLINE 5U

#define LOS_MEMORY_MANAGER_TASK_FLAG_BOOTSTRAP_HOSTED 0x0000000000000001ULL
#define LOS_MEMORY_MANAGER_TASK_FLAG_FIRST_USER_TASK 0x0000000000000002ULL
#define LOS_MEMORY_MANAGER_TASK_FLAG_SERVICE_READY 0x0000000000000004ULL

#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_FREE 0U
#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_READY 1U
#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_COMPLETE 2U

#define LOS_MEMORY_MANAGER_EVENT_SERVICE_ONLINE 1U
#define LOS_MEMORY_MANAGER_EVENT_SERVICE_READY_FOR_REQUESTS 2U
#define LOS_MEMORY_MANAGER_EVENT_SERVICE_FAULT 3U

#define LOS_MEMORY_MANAGER_REQUEST_MAILBOX_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_RESPONSE_MAILBOX_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_EVENT_MAILBOX_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_LAUNCH_BLOCK_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_SERVICE_STACK_PAGE_COUNT 8U
#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_COUNT 8U

#define LOS_MEMORY_MANAGER_BOOTSTRAP_SIGNATURE 0x5450424D4D534F4CULL
#define LOS_MEMORY_MANAGER_MAILBOX_SIGNATURE 0x58424D4D4D534F4CULL
#define LOS_MEMORY_MANAGER_LAUNCH_BLOCK_SIGNATURE 0x4B4C424D4D534F4CULL

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 Role;
    UINT32 State;
    UINT32 Reserved0;
    UINT64 Flags;
    UINT64 EndpointId;
    UINT64 MailboxPhysicalAddress;
    UINT64 MailboxSize;
    UINT64 PeerEndpointId;
} LOS_MEMORY_MANAGER_ENDPOINT_OBJECT;

typedef struct
{
    UINT64 KernelToService;
    UINT64 ServiceToKernel;
    UINT64 ServiceEvents;
} LOS_MEMORY_MANAGER_ENDPOINT_SET;

typedef struct
{
    UINT64 BaseVirtualAddress;
    UINT64 PageCount;
    UINT32 Type;
    UINT32 Flags;
    UINT64 BackingPhysicalAddress;
} LOS_MEMORY_MANAGER_RESERVED_VIRTUAL_REGION;

typedef struct
{
    UINT64 DesiredPhysicalAddress;
    UINT64 MinimumPhysicalAddress;
    UINT64 MaximumPhysicalAddress;
    UINT64 AlignmentBytes;
    UINT64 PageCount;
    UINT32 Flags;
    UINT32 Owner;
} LOS_MEMORY_MANAGER_ALLOCATE_FRAMES_REQUEST;

typedef struct
{
    UINT32 Status;
    UINT32 Reserved;
    UINT64 BaseAddress;
    UINT64 PageCount;
} LOS_MEMORY_MANAGER_ALLOCATE_FRAMES_RESULT;

typedef struct
{
    UINT64 AddressSpaceObjectPhysicalAddress;
    UINT64 VirtualAddress;
    UINT64 PhysicalAddress;
    UINT64 PageCount;
    UINT64 PageFlags;
    UINT32 Flags;
    UINT32 Reserved;
} LOS_MEMORY_MANAGER_MAP_PAGES_REQUEST;

typedef struct
{
    UINT32 Status;
    UINT32 Reserved;
    UINT64 AddressSpaceObjectPhysicalAddress;
    UINT64 PagesProcessed;
    UINT64 LastVirtualAddress;
} LOS_MEMORY_MANAGER_MAP_PAGES_RESULT;

typedef struct
{
    UINT64 AddressSpaceObjectPhysicalAddress;
    UINT64 VirtualAddress;
    UINT64 PageCount;
    UINT32 Flags;
    UINT32 Reserved;
} LOS_MEMORY_MANAGER_UNMAP_PAGES_REQUEST;

typedef struct
{
    UINT32 Status;
    UINT32 Reserved;
    UINT64 AddressSpaceObjectPhysicalAddress;
    UINT64 PagesProcessed;
    UINT64 LastVirtualAddress;
} LOS_MEMORY_MANAGER_UNMAP_PAGES_RESULT;

typedef struct
{
    UINT64 AddressSpaceObjectPhysicalAddress;
    UINT64 VirtualAddress;
    UINT64 PageCount;
    UINT64 PageFlags;
    UINT32 Flags;
    UINT32 Reserved;
} LOS_MEMORY_MANAGER_PROTECT_PAGES_REQUEST;
