/*
 * File Name: VirtualMemory.h
 * File Version: 0.3.23
 * Author: OpenAI
 * Email: dave66samaa@gmail.com
 * Creation Timestamp: 2026-04-07T07:24:34Z
 * Last Update Timestamp: 2026-04-10T18:55:00Z
 * Operating System Name: Liberation OS
 * Purpose: Implements low-level functionality for Liberation OS.
 */

#ifndef LOS_X64_VIRTUAL_MEMORY_H
#define LOS_X64_VIRTUAL_MEMORY_H

#include "KernelMain.h"

#define LOS_X64_MEMORY_MANAGER_HANDOFF_SIGNATURE 0x4D4D444E41484F4CULL
#define LOS_X64_MEMORY_MANAGER_HANDOFF_VERSION 3U
#define LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_QUERY_MEMORY_REGIONS 0x0000000000000001ULL
#define LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_RESERVE_FRAMES 0x0000000000000002ULL
#define LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_CLAIM_FRAMES 0x0000000000000004ULL
#define LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_MAP_PAGES 0x0000000000000008ULL
#define LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_UNMAP_PAGES 0x0000000000000010ULL

#define LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_PAGE_MAP LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_MAP_PAGES
#define LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_PAGE_UNMAP LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_UNMAP_PAGES
#define LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_FRAME_RESERVE LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_RESERVE_FRAMES
#define LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_FRAME_CLAIM LOS_X64_MEMORY_MANAGER_HANDOFF_FLAG_CLAIM_FRAMES

#define LOS_X64_MEMORY_OPERATION_STATUS_SUCCESS 0U
#define LOS_X64_MEMORY_OPERATION_STATUS_INVALID_ARGUMENT 1U
#define LOS_X64_MEMORY_OPERATION_STATUS_OUT_OF_RANGE 2U
#define LOS_X64_MEMORY_OPERATION_STATUS_NOT_SUPPORTED 3U
#define LOS_X64_MEMORY_OPERATION_STATUS_NO_RESOURCES 4U
#define LOS_X64_MEMORY_OPERATION_STATUS_CONFLICT 5U
#define LOS_X64_MEMORY_OPERATION_STATUS_NOT_FOUND 6U
#define LOS_X64_MEMORY_OPERATION_STATUS_ACCESS_DENIED 7U

#define LOS_X64_CLAIM_FRAMES_FLAG_BELOW_4G 0x00000001U
#define LOS_X64_CLAIM_FRAMES_FLAG_CONTIGUOUS 0x00000002U
#define LOS_X64_CLAIM_FRAMES_FLAG_EXACT_ADDRESS 0x00000004U

#define LOS_X64_MAP_PAGES_FLAG_ALLOW_REMAP 0x00000001U
#define LOS_X64_MAP_PAGES_FLAG_ALLOW_UNDISCOVERED_PHYSICAL 0x00000002U
#define LOS_X64_UNMAP_PAGES_FLAG_ALLOW_LARGE 0x00000001U

#define LOS_X64_PHYSICAL_FRAME_STATE_FREE 1U
#define LOS_X64_PHYSICAL_FRAME_STATE_RESERVED 2U
#define LOS_X64_PHYSICAL_FRAME_STATE_RUNTIME 3U
#define LOS_X64_PHYSICAL_FRAME_STATE_MMIO 4U

#define LOS_X64_PHYSICAL_FRAME_RESERVED_NONE 0U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_FIRMWARE 1U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_KERNEL_IMAGE 2U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_BOOT_CONTEXT 3U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_MEMORY_MAP 4U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_BOOTSTRAP_PAGE_TABLES 5U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_BOOTSTRAP_STACK 6U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_KERNEL_STACK 7U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_GDT 8U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_IDT 9U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_DEBUG 10U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_KERNEL_FONT 11U
#define LOS_X64_PHYSICAL_FRAME_RESERVED_CLAIMED 12U

#define LOS_X64_MEMORY_REGION_TYPE_USABLE 1U
#define LOS_X64_MEMORY_REGION_TYPE_BOOT_RESERVED 2U
#define LOS_X64_MEMORY_REGION_TYPE_RUNTIME 3U
#define LOS_X64_MEMORY_REGION_TYPE_MMIO 4U
#define LOS_X64_MEMORY_REGION_TYPE_ACPI_NVS 5U
#define LOS_X64_MEMORY_REGION_TYPE_FIRMWARE_RESERVED 6U
#define LOS_X64_MEMORY_REGION_TYPE_UNUSABLE 7U

#define LOS_X64_MEMORY_REGION_FLAG_OVERLAY 0x00000001U
#define LOS_X64_MEMORY_REGION_FLAG_DIRECT_MAP 0x00000002U
#define LOS_X64_MEMORY_REGION_FLAG_CLAIMED 0x00000004U

#define LOS_X64_MEMORY_REGION_OWNER_NONE LOS_X64_PHYSICAL_FRAME_RESERVED_NONE
#define LOS_X64_MEMORY_REGION_OWNER_FIRMWARE LOS_X64_PHYSICAL_FRAME_RESERVED_FIRMWARE
#define LOS_X64_MEMORY_REGION_OWNER_KERNEL_IMAGE LOS_X64_PHYSICAL_FRAME_RESERVED_KERNEL_IMAGE
#define LOS_X64_MEMORY_REGION_OWNER_BOOT_CONTEXT LOS_X64_PHYSICAL_FRAME_RESERVED_BOOT_CONTEXT
#define LOS_X64_MEMORY_REGION_OWNER_MEMORY_MAP LOS_X64_PHYSICAL_FRAME_RESERVED_MEMORY_MAP
#define LOS_X64_MEMORY_REGION_OWNER_BOOTSTRAP_PAGE_TABLES LOS_X64_PHYSICAL_FRAME_RESERVED_BOOTSTRAP_PAGE_TABLES
#define LOS_X64_MEMORY_REGION_OWNER_BOOTSTRAP_STACK LOS_X64_PHYSICAL_FRAME_RESERVED_BOOTSTRAP_STACK
#define LOS_X64_MEMORY_REGION_OWNER_KERNEL_STACK LOS_X64_PHYSICAL_FRAME_RESERVED_KERNEL_STACK
#define LOS_X64_MEMORY_REGION_OWNER_GDT LOS_X64_PHYSICAL_FRAME_RESERVED_GDT
#define LOS_X64_MEMORY_REGION_OWNER_IDT LOS_X64_PHYSICAL_FRAME_RESERVED_IDT
#define LOS_X64_MEMORY_REGION_OWNER_DEBUG LOS_X64_PHYSICAL_FRAME_RESERVED_DEBUG
#define LOS_X64_MEMORY_REGION_OWNER_KERNEL_FONT LOS_X64_PHYSICAL_FRAME_RESERVED_KERNEL_FONT
#define LOS_X64_MEMORY_REGION_OWNER_CLAIMED LOS_X64_PHYSICAL_FRAME_RESERVED_CLAIMED

#define LOS_X64_MEMORY_REGION_SOURCE_EFI 1U
#define LOS_X64_MEMORY_REGION_SOURCE_BOOTSTRAP 2U
#define LOS_X64_MEMORY_REGION_SOURCE_KERNEL 3U
#define LOS_X64_MEMORY_REGION_SOURCE_RUNTIME 4U

typedef struct
{
    UINT64 BaseAddress;
    UINT64 PageCount;
    UINT32 State;
    UINT32 SourceType;
    UINT32 ReservedKind;
    UINT32 Reserved;
    UINT64 Attributes;
} LOS_X64_PHYSICAL_FRAME_REGION;

typedef struct
{
    UINT64 Base;
    UINT64 Length;
    UINT32 Type;
    UINT32 Flags;
    UINT32 Owner;
    UINT32 Source;
} LOS_X64_MEMORY_REGION;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 Reserved;
    UINT64 Flags;
    UINT64 RegionDatabaseAddress;
    UINT64 RegionCount;
    UINT64 RegionEntrySize;
    UINT64 TotalUsableBytes;
    UINT64 TotalBootstrapReservedBytes;
    UINT64 TotalFirmwareReservedBytes;
    UINT64 TotalRuntimeBytes;
    UINT64 TotalMmioBytes;
    UINT64 TotalAcpiBytes;
    UINT64 TotalUnusableBytes;
    UINT64 TotalAddressSpaceGapBytes;
    UINT64 HighestUsablePhysicalAddress;
} LOS_X64_MEMORY_MANAGER_HANDOFF;

typedef struct
{
    UINT32 Status;
    UINT32 Reserved;
    UINT64 TotalRegionCount;
    UINT64 RegionsWritten;
    UINT64 RegionEntrySize;
} LOS_X64_QUERY_MEMORY_REGIONS_RESULT;

typedef struct
{
    UINT64 PhysicalAddress;
    UINT64 Length;
    UINT32 Owner;
    UINT32 Reserved;
} LOS_X64_RESERVE_FRAMES_REQUEST;

typedef struct
{
    UINT32 Status;
    UINT32 Reserved;
    UINT64 PagesReserved;
    UINT64 RangeBase;
    UINT64 RangeLength;
} LOS_X64_RESERVE_FRAMES_RESULT;

typedef struct
{
    UINT64 DesiredPhysicalAddress;
    UINT64 MinimumPhysicalAddress;
    UINT64 MaximumPhysicalAddress;
    UINT64 AlignmentBytes;
    UINT64 PageCount;
    UINT32 Flags;
    UINT32 Owner;
} LOS_X64_CLAIM_FRAMES_REQUEST;

typedef struct
{
    UINT32 Status;
    UINT32 Reserved;
    UINT64 BaseAddress;
    UINT64 PageCount;
} LOS_X64_CLAIM_FRAMES_RESULT;

typedef struct
{
    UINT64 PhysicalAddress;
    UINT64 PageCount;
} LOS_X64_FREE_FRAMES_REQUEST;

typedef struct
{
    UINT32 Status;
    UINT32 Reserved;
    UINT64 BaseAddress;
    UINT64 PageCount;
} LOS_X64_FREE_FRAMES_RESULT;

typedef struct
{
    UINT64 PageMapLevel4PhysicalAddress;
    UINT64 VirtualAddress;
    UINT64 PhysicalAddress;
    UINT64 PageCount;
    UINT64 PageFlags;
    UINT32 Flags;
    UINT32 Reserved;
} LOS_X64_MAP_PAGES_REQUEST;

typedef struct
{
    UINT32 Status;
    UINT32 Reserved;
    UINT64 TargetPageMapLevel4PhysicalAddress;
    UINT64 PagesProcessed;
    UINT64 LastVirtualAddress;
} LOS_X64_MAP_PAGES_RESULT;

typedef struct
{
    UINT64 PageMapLevel4PhysicalAddress;
    UINT64 VirtualAddress;
    UINT64 PageCount;
    UINT32 Flags;
    UINT32 Reserved;
} LOS_X64_UNMAP_PAGES_REQUEST;

typedef struct
{
    UINT32 Status;
    UINT32 Reserved;
    UINT64 TargetPageMapLevel4PhysicalAddress;
    UINT64 PagesProcessed;
    UINT64 LastVirtualAddress;
} LOS_X64_UNMAP_PAGES_RESULT;

void LosX64InitializeVirtualMemory(const LOS_BOOT_CONTEXT *BootContext);
void LosX64ReportHigherHalfEntryJump(void);
void LosX64DescribeVirtualMemoryLayout(void);
void LosX64DescribeBootMemoryMap(const LOS_BOOT_CONTEXT *BootContext);
void LosX64DescribePhysicalMemoryState(void);
void LosX64DescribeMemoryManagerHandoff(void);
void LosX64QueryMemoryRegions(LOS_X64_MEMORY_REGION *Buffer, UINTN BufferRegionCapacity, LOS_X64_QUERY_MEMORY_REGIONS_RESULT *Result);
void LosX64ReserveFrames(const LOS_X64_RESERVE_FRAMES_REQUEST *Request, LOS_X64_RESERVE_FRAMES_RESULT *Result);
void LosX64ClaimFrames(const LOS_X64_CLAIM_FRAMES_REQUEST *Request, LOS_X64_CLAIM_FRAMES_RESULT *Result);
void LosX64MapPages(const LOS_X64_MAP_PAGES_REQUEST *Request, LOS_X64_MAP_PAGES_RESULT *Result);
void LosX64UnmapPages(const LOS_X64_UNMAP_PAGES_REQUEST *Request, LOS_X64_UNMAP_PAGES_RESULT *Result);
BOOLEAN LosX64TryTranslateKernelVirtualToPhysical(UINT64 VirtualAddress, UINT64 *PhysicalAddress);
BOOLEAN LosX64MapVirtualPage(UINT64 VirtualAddress, UINT64 PhysicalAddress, UINT64 Flags);
BOOLEAN LosX64MapVirtualRange(UINT64 VirtualAddress, UINT64 PhysicalAddress, UINTN PageCount, UINT64 Flags);
BOOLEAN LosX64UnmapVirtualPage(UINT64 VirtualAddress);
BOOLEAN LosX64UnmapVirtualRange(UINT64 VirtualAddress, UINTN PageCount);
void *LosX64GetDirectMapVirtualAddress(UINT64 PhysicalAddress, UINT64 Length);
void *LosX64GetKernelStackTop(void);
BOOLEAN LosX64ReservePhysicalRange(UINT64 PhysicalAddress, UINT64 Length, UINT32 ReservationKind);
BOOLEAN LosX64ClaimPhysicalPages(UINT64 PhysicalAddress, UINT64 PageCount);
UINTN LosX64GetPhysicalFrameRegionCount(void);
const LOS_X64_PHYSICAL_FRAME_REGION *LosX64GetPhysicalFrameRegion(UINTN Index);
UINTN LosX64GetMemoryRegionCount(void);
const LOS_X64_MEMORY_REGION *LosX64GetMemoryRegion(UINTN Index);
const LOS_X64_MEMORY_MANAGER_HANDOFF *LosX64GetMemoryManagerHandoff(void);

#endif
