#ifndef LOS_MEMORY_MANAGER_BOOTSTRAP_H
#define LOS_MEMORY_MANAGER_BOOTSTRAP_H

#include "KernelMain.h"
#include "VirtualMemory.h"

#define LOS_MEMORY_MANAGER_BOOTSTRAP_VERSION 3U
#define LOS_MEMORY_MANAGER_SERVICE_PATH_CHARACTERS 128U
#define LOS_MEMORY_MANAGER_SERVICE_NAME "MemoryManager"

#define LOS_MEMORY_MANAGER_ENDPOINT_KERNEL_TO_SERVICE 0x4D4D535256000001ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_SERVICE_TO_KERNEL 0x4D4D535256000002ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_SERVICE_EVENTS 0x4D4D535256000003ULL

#define LOS_MEMORY_MANAGER_OPERATION_QUERY_MEMORY_REGIONS 1U
#define LOS_MEMORY_MANAGER_OPERATION_RESERVE_FRAMES 2U
#define LOS_MEMORY_MANAGER_OPERATION_CLAIM_FRAMES 3U
#define LOS_MEMORY_MANAGER_OPERATION_MAP_PAGES 4U
#define LOS_MEMORY_MANAGER_OPERATION_UNMAP_PAGES 5U

#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_OFFLINE 0U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_DEFINED 1U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_LAUNCHED 2U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_STAGED 3U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_IMAGE_READY 4U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_READY 5U

#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_KERNEL_LOW_LEVEL_FRAMES 0x0000000000000001ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_KERNEL_LOW_LEVEL_PAGING 0x0000000000000002ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_ENDPOINT_BRIDGE 0x0000000000000004ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_PROBE_COMPLETE 0x0000000000000008ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_TRANSPORT_READY 0x0000000000000010ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_LAUNCH_BLOCK_READY 0x0000000000000020ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_STACK_READY 0x0000000000000040ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_IMAGE_READY 0x0000000000000080ULL

#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_FREE 0U
#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_READY 1U
#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_COMPLETE 2U

#define LOS_MEMORY_MANAGER_REQUEST_MAILBOX_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_RESPONSE_MAILBOX_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_EVENT_MAILBOX_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_LAUNCH_BLOCK_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_SERVICE_STACK_PAGE_COUNT 8U
#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_COUNT 8U

typedef struct
{
    UINT64 KernelToService;
    UINT64 ServiceToKernel;
    UINT64 ServiceEvents;
} LOS_MEMORY_MANAGER_ENDPOINT_SET;

typedef struct
{
    UINT32 Operation;
    UINT32 Reserved0;
    UINT64 RequestId;
    union
    {
        struct
        {
            LOS_X64_MEMORY_REGION *Buffer;
            UINTN BufferRegionCapacity;
        } QueryMemoryRegions;
        LOS_X64_RESERVE_FRAMES_REQUEST ReserveFrames;
        LOS_X64_CLAIM_FRAMES_REQUEST ClaimFrames;
        LOS_X64_MAP_PAGES_REQUEST MapPages;
        LOS_X64_UNMAP_PAGES_REQUEST UnmapPages;
    } Payload;
} LOS_MEMORY_MANAGER_REQUEST_MESSAGE;

typedef struct
{
    UINT32 Operation;
    UINT32 Status;
    UINT64 RequestId;
    union
    {
        LOS_X64_QUERY_MEMORY_REGIONS_RESULT QueryMemoryRegions;
        LOS_X64_RESERVE_FRAMES_RESULT ReserveFrames;
        LOS_X64_CLAIM_FRAMES_RESULT ClaimFrames;
        LOS_X64_MAP_PAGES_RESULT MapPages;
        LOS_X64_UNMAP_PAGES_RESULT UnmapPages;
    } Payload;
} LOS_MEMORY_MANAGER_RESPONSE_MESSAGE;

typedef struct
{
    UINT32 SlotState;
    UINT32 Reserved;
    UINT64 Sequence;
    LOS_MEMORY_MANAGER_REQUEST_MESSAGE Message;
} LOS_MEMORY_MANAGER_REQUEST_SLOT;

typedef struct
{
    UINT32 SlotState;
    UINT32 Reserved;
    UINT64 Sequence;
    LOS_MEMORY_MANAGER_RESPONSE_MESSAGE Message;
} LOS_MEMORY_MANAGER_RESPONSE_SLOT;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 Reserved;
    UINT64 EndpointId;
    UINT64 SlotCount;
    UINT64 ProduceIndex;
    UINT64 ConsumeIndex;
} LOS_MEMORY_MANAGER_MAILBOX_HEADER;

typedef struct
{
    LOS_MEMORY_MANAGER_MAILBOX_HEADER Header;
    LOS_MEMORY_MANAGER_REQUEST_SLOT Slots[LOS_MEMORY_MANAGER_MAILBOX_SLOT_COUNT];
} LOS_MEMORY_MANAGER_REQUEST_MAILBOX;

typedef struct
{
    LOS_MEMORY_MANAGER_MAILBOX_HEADER Header;
    LOS_MEMORY_MANAGER_RESPONSE_SLOT Slots[LOS_MEMORY_MANAGER_MAILBOX_SLOT_COUNT];
} LOS_MEMORY_MANAGER_RESPONSE_MAILBOX;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 State;
    UINT64 Flags;
    LOS_MEMORY_MANAGER_ENDPOINT_SET Endpoints;
    UINT64 SupportedOperations;
    UINT64 ServiceImagePhysicalAddress;
    UINT64 ServiceImageSize;
    UINT64 ServiceEntryVirtualAddress;
    UINT64 ServiceStackPhysicalAddress;
    UINT64 ServiceStackPageCount;
    UINT64 RequestMailboxPhysicalAddress;
    UINT64 RequestMailboxSize;
    UINT64 ResponseMailboxPhysicalAddress;
    UINT64 ResponseMailboxSize;
    UINT64 EventMailboxPhysicalAddress;
    UINT64 EventMailboxSize;
    UINT64 LaunchBlockPhysicalAddress;
    UINT64 LaunchBlockSize;
    CHAR16 ServicePath[LOS_MEMORY_MANAGER_SERVICE_PATH_CHARACTERS];
} LOS_MEMORY_MANAGER_BOOTSTRAP_INFO;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 Reserved;
    UINT64 Flags;
    LOS_MEMORY_MANAGER_ENDPOINT_SET Endpoints;
    UINT64 RequestMailboxPhysicalAddress;
    UINT64 RequestMailboxSize;
    UINT64 ResponseMailboxPhysicalAddress;
    UINT64 ResponseMailboxSize;
    UINT64 EventMailboxPhysicalAddress;
    UINT64 EventMailboxSize;
    UINT64 ServiceStackPhysicalAddress;
    UINT64 ServiceStackPageCount;
    UINT64 ServiceStackTopPhysicalAddress;
    UINT64 ServiceImagePhysicalAddress;
    UINT64 ServiceImageSize;
    UINT64 ServiceEntryVirtualAddress;
    CHAR16 ServicePath[LOS_MEMORY_MANAGER_SERVICE_PATH_CHARACTERS];
} LOS_MEMORY_MANAGER_LAUNCH_BLOCK;

void LosInitializeMemoryManagerBootstrap(const LOS_BOOT_CONTEXT *BootContext);
void LosLaunchMemoryManagerBootstrap(void);
void LosDescribeMemoryManagerBootstrap(void);
BOOLEAN LosIsMemoryManagerBootstrapReady(void);
const LOS_MEMORY_MANAGER_BOOTSTRAP_INFO *LosGetMemoryManagerBootstrapInfo(void);
const LOS_MEMORY_MANAGER_LAUNCH_BLOCK *LosGetMemoryManagerLaunchBlock(void);
void LosMemoryManagerSendQueryMemoryRegions(LOS_X64_MEMORY_REGION *Buffer, UINTN BufferRegionCapacity, LOS_X64_QUERY_MEMORY_REGIONS_RESULT *Result);
void LosMemoryManagerSendReserveFrames(const LOS_X64_RESERVE_FRAMES_REQUEST *Request, LOS_X64_RESERVE_FRAMES_RESULT *Result);
void LosMemoryManagerSendClaimFrames(const LOS_X64_CLAIM_FRAMES_REQUEST *Request, LOS_X64_CLAIM_FRAMES_RESULT *Result);
void LosMemoryManagerSendMapPages(const LOS_X64_MAP_PAGES_REQUEST *Request, LOS_X64_MAP_PAGES_RESULT *Result);
void LosMemoryManagerSendUnmapPages(const LOS_X64_UNMAP_PAGES_REQUEST *Request, LOS_X64_UNMAP_PAGES_RESULT *Result);

#endif
