/*
 * File Name: CapabilitiesServiceAbi.h
 * File Version: 0.3.31
 * Author: OpenAI
 * Email: dave66samaa@gmail.com
 * Creation Timestamp: 2026-04-07T11:02:18Z
 * Last Update Timestamp: 2026-04-09T19:40:00Z
 * Operating System Name: Liberation OS
 * Purpose: Declares shared interfaces and data structures for Liberation OS.
 */

#ifndef LOS_PUBLIC_CAPABILITIES_SERVICE_ABI_H
#define LOS_PUBLIC_CAPABILITIES_SERVICE_ABI_H

#include "Efi.h"

#define LOS_CAPABILITIES_SERVICE_VERSION 16U
#define LOS_CAPABILITIES_SERVICE_NAME_LENGTH 32U
#define LOS_CAPABILITIES_SERVICE_NAMESPACE_LENGTH 32U
#define LOS_CAPABILITIES_SERVICE_MAX_ENTRIES 128U
#define LOS_CAPABILITIES_BOOTSTRAP_CONTEXT_MAX_BLOCKS 8U
#define LOS_CAPABILITIES_BOOTSTRAP_CONTEXT_MAX_GRANTS_PER_BLOCK 16U
#define LOS_CAPABILITIES_BOOTSTRAP_CONTEXT_MAX_ASSIGNMENTS 16U
#define LOS_CAPABILITIES_BOOTSTRAP_CONTEXT_MAX_EVENTS 64U
#define LOS_CAPABILITIES_PRINCIPAL_NAME_LENGTH 32U
#define LOS_CAPABILITIES_AUTHORISER_NAME_LENGTH 32U
#define LOS_CAPABILITIES_RUNTIME_MAX_GRANTS 128U
#define LOS_CAPABILITIES_RUNTIME_MAX_EVENTS 256U

#define LOS_CAPABILITIES_TRANSPORT_EXPORT_SIGNATURE 0x5458504341505343ULL
#define LOS_CAPABILITIES_TRANSPORT_BINDING_SIGNATURE 0x424E444341505343ULL

#define LOS_CAPABILITIES_SERVICE_STATUS_TRANSPORT_OFFLINE 9U
#define LOS_CAPABILITIES_SERVICE_STATUS_TRANSPORT_STALE 10U
#define LOS_CAPABILITIES_SERVICE_STATUS_TARGET_MISMATCH 11U
#define LOS_CAPABILITIES_SERVICE_STATUS_AUTH_FAILED 12U
#define LOS_CAPABILITIES_SERVICE_STATUS_REPLAY_DETECTED 13U
#define LOS_CAPABILITIES_SERVICE_STATUS_SESSION_REJECTED 14U
#define LOS_CAPABILITIES_SERVICE_STATUS_SECURITY_MODE_MISMATCH 15U

#define LOS_CAPABILITIES_SERVICE_STATUS_SUCCESS 0U
#define LOS_CAPABILITIES_SERVICE_STATUS_INVALID_PARAMETER 1U
#define LOS_CAPABILITIES_SERVICE_STATUS_TABLE_FULL 2U
#define LOS_CAPABILITIES_SERVICE_STATUS_NOT_FOUND 3U
#define LOS_CAPABILITIES_SERVICE_STATUS_ALREADY_PRESENT 4U
#define LOS_CAPABILITIES_SERVICE_STATUS_UNSUPPORTED 5U
#define LOS_CAPABILITIES_SERVICE_STATUS_ACCESS_DENIED 6U
#define LOS_CAPABILITIES_SERVICE_STATUS_INVALID_STATE 7U
#define LOS_CAPABILITIES_SERVICE_STATUS_NOT_AUTHORISED 8U

#define LOS_CAPABILITIES_SERVICE_FLAG_GRANTED   0x00000001U
#define LOS_CAPABILITIES_SERVICE_FLAG_DELEGABLE 0x00000002U
#define LOS_CAPABILITIES_SERVICE_FLAG_AUDIT     0x00000004U
#define LOS_CAPABILITIES_SERVICE_FLAG_BOOTSTRAP 0x00000008U

#define LOS_CAPABILITIES_SERVICE_CLASS_KERNEL   1U
#define LOS_CAPABILITIES_SERVICE_CLASS_SERVICE  2U
#define LOS_CAPABILITIES_SERVICE_CLASS_USER     3U

#define LOS_CAPABILITIES_SERVICE_EVENT_ONLINE   1U
#define LOS_CAPABILITIES_SERVICE_EVENT_GRANTED  2U
#define LOS_CAPABILITIES_SERVICE_EVENT_REVOKED  3U

#define LOS_CAPABILITIES_SERVICE_QUERY_EXACT    1U
#define LOS_CAPABILITIES_SERVICE_QUERY_PREFIX   2U

#define LOS_CAPABILITIES_PRINCIPAL_TYPE_USER        1U
#define LOS_CAPABILITIES_PRINCIPAL_TYPE_PROFILE     2U
#define LOS_CAPABILITIES_PRINCIPAL_TYPE_SERVICE     3U
#define LOS_CAPABILITIES_PRINCIPAL_TYPE_TASK        4U
#define LOS_CAPABILITIES_PRINCIPAL_TYPE_SESSION     5U
#define LOS_CAPABILITIES_PRINCIPAL_TYPE_BOOTSTRAP   6U

#define LOS_CAPABILITIES_GRANT_MODE_DIRECT          1U
#define LOS_CAPABILITIES_GRANT_MODE_INHERITED       2U
#define LOS_CAPABILITIES_GRANT_MODE_DELEGATED       3U
#define LOS_CAPABILITIES_GRANT_MODE_BOOTSTRAP       4U

#define LOS_CAPABILITIES_GRANT_STATE_ACTIVE         1U
#define LOS_CAPABILITIES_GRANT_STATE_SUSPENDED      2U
#define LOS_CAPABILITIES_GRANT_STATE_REVOKED        3U
#define LOS_CAPABILITIES_GRANT_STATE_EXPIRED        4U

#define LOS_CAPABILITIES_AUTHORISER_BOOT_POLICY     1U
#define LOS_CAPABILITIES_AUTHORISER_KERNEL          2U
#define LOS_CAPABILITIES_AUTHORISER_SERVICE         3U
#define LOS_CAPABILITIES_AUTHORISER_USER            4U
#define LOS_CAPABILITIES_AUTHORISER_DELEGATED       5U

#define LOS_CAPABILITIES_GRANT_EVENT_CREATED        1U
#define LOS_CAPABILITIES_GRANT_EVENT_REVOKED        2U
#define LOS_CAPABILITIES_GRANT_EVENT_SUSPENDED      3U
#define LOS_CAPABILITIES_GRANT_EVENT_RESTORED       4U
#define LOS_CAPABILITIES_GRANT_EVENT_IMPORTED       5U

#define LOS_CAPABILITIES_MUTATION_GRANT             1U
#define LOS_CAPABILITIES_MUTATION_REVOKE            2U
#define LOS_CAPABILITIES_MUTATION_SUSPEND           3U
#define LOS_CAPABILITIES_MUTATION_RESTORE           4U

#define LOS_CAPABILITIES_ACCESS_RIGHT_QUERY          1U
#define LOS_CAPABILITIES_ACCESS_RIGHT_MUTATE         2U

#define LOS_CAPABILITIES_ENDPOINT_REQUEST 0x4341505352560001ULL
#define LOS_CAPABILITIES_ENDPOINT_RESPONSE 0x4341505352560002ULL

#define LOS_CAPABILITIES_ENDPOINT_ROLE_RECEIVE 1U
#define LOS_CAPABILITIES_ENDPOINT_ROLE_REPLY 2U

#define LOS_CAPABILITIES_ENDPOINT_STATE_OFFLINE 0U
#define LOS_CAPABILITIES_ENDPOINT_STATE_DEFINED 1U
#define LOS_CAPABILITIES_ENDPOINT_STATE_READY 2U
#define LOS_CAPABILITIES_ENDPOINT_STATE_ONLINE 3U

#define LOS_CAPABILITIES_ENDPOINT_FLAG_SERVICE_VISIBLE 0x0000000000000001ULL
#define LOS_CAPABILITIES_ENDPOINT_FLAG_MAILBOX_ATTACHED 0x0000000000000002ULL
#define LOS_CAPABILITIES_ENDPOINT_FLAG_ISOLATED_TRANSPORT 0x0000000000000004ULL
#define LOS_CAPABILITIES_ENDPOINT_FLAG_MESSAGE_AUTH      0x0000000000000008ULL
#define LOS_CAPABILITIES_ENDPOINT_FLAG_ANTI_REPLAY       0x0000000000000010ULL
#define LOS_CAPABILITIES_ENDPOINT_FLAG_IDENTITY_BOUND     0x0000000000000020ULL
#define LOS_CAPABILITIES_ENDPOINT_FLAG_SESSION_ESTABLISHED 0x0000000000000040ULL

#define LOS_CAPABILITIES_MAILBOX_SLOT_FREE 0U
#define LOS_CAPABILITIES_MAILBOX_SLOT_READY 1U
#define LOS_CAPABILITIES_MAILBOX_SLOT_COMPLETE 2U
#define LOS_CAPABILITIES_MAILBOX_SLOT_COUNT 8U
#define LOS_CAPABILITIES_MAILBOX_SIGNATURE 0x5842434150534F4CULL

#define LOS_CAPABILITIES_ENDPOINT_FLAG_CONFIDENTIAL_CHANNEL  0x0000000000000080ULL
#define LOS_CAPABILITIES_ENDPOINT_FLAG_POLICY_DRIVEN_SECURITY 0x0000000000000100ULL

#define LOS_CAPABILITIES_ENDPOINT_CLASS_CONTROL 1U
#define LOS_CAPABILITIES_ENDPOINT_CLASS_DATA    2U
#define LOS_CAPABILITIES_ENDPOINT_CLASS_ADMIN   3U

#define LOS_CAPABILITIES_SECURITY_MODE_PLAINTEXT      0U
#define LOS_CAPABILITIES_SECURITY_MODE_AUTHENTICATED  1U
#define LOS_CAPABILITIES_SECURITY_MODE_CONFIDENTIAL   2U

typedef struct
{
    UINT32 Version;
    UINT32 CapabilityClass;
    UINT32 Flags;
    UINT32 Reserved;
    UINT64 CapabilityId;
    char Namespace[LOS_CAPABILITIES_SERVICE_NAMESPACE_LENGTH];
    char Name[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
} LOS_CAPABILITIES_SERVICE_RECORD;

typedef struct
{
    UINT32 Version;
    UINT32 QueryType;
    UINT32 Reserved0;
    UINT32 Reserved1;
    char Namespace[LOS_CAPABILITIES_SERVICE_NAMESPACE_LENGTH];
    char Name[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
} LOS_CAPABILITIES_SERVICE_QUERY;

typedef struct
{
    UINT32 Version;
    UINT32 Status;
    UINT32 MatchCount;
    UINT32 Reserved;
    LOS_CAPABILITIES_SERVICE_RECORD Record;
} LOS_CAPABILITIES_SERVICE_QUERY_RESULT;

typedef struct
{
    UINT32 Version;
    UINT32 Status;
    UINT32 Count;
    UINT32 Capacity;
} LOS_CAPABILITIES_SERVICE_ENUMERATION_HEADER;

typedef struct
{
    UINT32 Version;
    UINT32 CapabilityClass;
    UINT32 Flags;
    UINT32 GrantMode;
    UINT32 State;
    UINT32 AuthoriserType;
    UINT32 Reserved0;
    UINT32 Reserved1;
    UINT64 CapabilityId;
    UINT64 GrantId;
    UINT64 ParentGrantId;
    UINT64 GrantedAtUtc;
    UINT64 EffectiveFromUtc;
    UINT64 EffectiveUntilUtc;
    UINT64 RevokedAtUtc;
    UINT64 SuspendedAtUtc;
    char Namespace[LOS_CAPABILITIES_SERVICE_NAMESPACE_LENGTH];
    char Name[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
    char AuthoriserName[LOS_CAPABILITIES_AUTHORISER_NAME_LENGTH];
} LOS_CAPABILITY_GRANT_ENTRY;

typedef struct
{
    UINT32 Version;
    UINT32 Flags;
    UINT32 PrincipalType;
    UINT32 Reserved;
    UINT64 PrincipalId;
    UINT64 ProfileId;
    UINT32 GrantCount;
    UINT32 Capacity;
    char PrincipalName[LOS_CAPABILITIES_PRINCIPAL_NAME_LENGTH];
    char ProfileName[LOS_CAPABILITIES_PRINCIPAL_NAME_LENGTH];
    LOS_CAPABILITY_GRANT_ENTRY Grants[LOS_CAPABILITIES_BOOTSTRAP_CONTEXT_MAX_GRANTS_PER_BLOCK];
} LOS_CAPABILITY_GRANT_BLOCK;

typedef struct
{
    UINT32 Version;
    UINT32 Flags;
    UINT32 PrincipalType;
    UINT32 AuthoriserType;
    UINT64 PrincipalId;
    UINT64 ProfileId;
    UINT64 AssignedAtUtc;
    char PrincipalName[LOS_CAPABILITIES_PRINCIPAL_NAME_LENGTH];
    char ProfileName[LOS_CAPABILITIES_PRINCIPAL_NAME_LENGTH];
    char AuthoriserName[LOS_CAPABILITIES_AUTHORISER_NAME_LENGTH];
} LOS_CAPABILITY_PROFILE_ASSIGNMENT;

typedef struct
{
    UINT32 Version;
    UINT32 EventType;
    UINT32 ActorType;
    UINT32 Reserved;
    UINT64 EventId;
    UINT64 GrantId;
    UINT64 EventAtUtc;
    UINT64 PrincipalId;
    char PrincipalName[LOS_CAPABILITIES_PRINCIPAL_NAME_LENGTH];
    char CapabilityNamespace[LOS_CAPABILITIES_SERVICE_NAMESPACE_LENGTH];
    char CapabilityName[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
    char ActorName[LOS_CAPABILITIES_AUTHORISER_NAME_LENGTH];
} LOS_CAPABILITY_GRANT_EVENT;

typedef struct
{
    UINT32 Version;
    UINT32 Flags;
    UINT32 BlockCount;
    UINT32 Capacity;
    UINT32 AssignmentCount;
    UINT32 AssignmentCapacity;
    UINT32 EventCount;
    UINT32 EventCapacity;
    LOS_CAPABILITY_GRANT_BLOCK Blocks[LOS_CAPABILITIES_BOOTSTRAP_CONTEXT_MAX_BLOCKS];
    LOS_CAPABILITY_PROFILE_ASSIGNMENT Assignments[LOS_CAPABILITIES_BOOTSTRAP_CONTEXT_MAX_ASSIGNMENTS];
    LOS_CAPABILITY_GRANT_EVENT Events[LOS_CAPABILITIES_BOOTSTRAP_CONTEXT_MAX_EVENTS];
} LOS_CAPABILITIES_BOOTSTRAP_CONTEXT;

typedef struct
{
    UINT32 Version;
    UINT32 PrincipalType;
    UINT32 AccessRight;
    UINT32 Reserved0;
    UINT64 PrincipalId;
    char PrincipalName[LOS_CAPABILITIES_PRINCIPAL_NAME_LENGTH];
    char Namespace[LOS_CAPABILITIES_SERVICE_NAMESPACE_LENGTH];
    char Name[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
} LOS_CAPABILITIES_ACCESS_REQUEST;

typedef struct
{
    UINT32 Version;
    UINT32 Status;
    UINT32 Granted;
    UINT32 Reserved0;
    UINT64 MatchingGrantId;
} LOS_CAPABILITIES_ACCESS_RESULT;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 Role;
    UINT32 State;
    UINT32 EndpointClass;
    UINT32 SecurityMode;
    UINT64 Flags;
    UINT64 EndpointId;
    UINT64 MailboxAddress;
    UINT64 MailboxSize;
    UINT64 PeerEndpointId;
} LOS_CAPABILITIES_ENDPOINT_OBJECT;

typedef struct
{
    UINT32 Version;
    UINT32 Reserved0;
    UINT64 SlotCount;
    UINT64 ProduceIndex;
    UINT64 ConsumeIndex;
    UINT64 Signature;
} LOS_CAPABILITIES_MAILBOX_HEADER;

typedef struct
{
    UINT32 SlotState;
    UINT32 Reserved0;
    UINT32 EndpointClass;
    UINT32 SecurityMode;
    UINT64 Sequence;
    UINT64 SessionId;
    UINT64 Nonce;
    UINT64 AuthTag;
    LOS_CAPABILITIES_ACCESS_REQUEST Message;
} LOS_CAPABILITIES_ACCESS_REQUEST_SLOT;

typedef struct
{
    LOS_CAPABILITIES_MAILBOX_HEADER Header;
    LOS_CAPABILITIES_ACCESS_REQUEST_SLOT Slots[LOS_CAPABILITIES_MAILBOX_SLOT_COUNT];
} LOS_CAPABILITIES_REQUEST_MAILBOX;

typedef struct
{
    UINT32 SlotState;
    UINT32 Reserved0;
    UINT32 EndpointClass;
    UINT32 SecurityMode;
    UINT64 Sequence;
    UINT64 SessionId;
    UINT64 Nonce;
    UINT64 AuthTag;
    LOS_CAPABILITIES_ACCESS_RESULT Message;
} LOS_CAPABILITIES_ACCESS_RESPONSE_SLOT;

typedef struct
{
    LOS_CAPABILITIES_MAILBOX_HEADER Header;
    LOS_CAPABILITIES_ACCESS_RESPONSE_SLOT Slots[LOS_CAPABILITIES_MAILBOX_SLOT_COUNT];
} LOS_CAPABILITIES_RESPONSE_MAILBOX;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 Reserved0;
    UINT64 Generation;
    UINT64 RequestEndpointId;
    UINT64 ResponseEndpointId;
    UINT64 RequestMailboxAddress;
    UINT64 ResponseMailboxAddress;
    UINT64 RequestMailboxSize;
    UINT64 ResponseMailboxSize;
    UINT64 Flags;
    UINT32 ServiceClass;
    UINT32 TransportState;
    UINT32 EndpointClass;
    UINT32 MinimumSecurityMode;
    char ServiceName[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
} LOS_CAPABILITIES_TRANSPORT_EXPORT;

typedef struct
{
    UINT32 Version;
    UINT32 PrincipalType;
    UINT32 EndpointRole;
    UINT32 Reserved0;
    UINT64 PrincipalId;
    char PrincipalName[LOS_CAPABILITIES_PRINCIPAL_NAME_LENGTH];
    char ServiceName[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
    char EndpointName[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
} LOS_CAPABILITIES_ENDPOINT_IDENTITY;

typedef struct
{
    UINT32 Version;
    UINT32 PrincipalType;
    UINT32 RequiredEndpointRole;
    UINT32 RequiredFlags;
    UINT32 TargetEndpointClass;
    UINT32 DesiredSecurityMode;
    UINT64 PrincipalId;
    UINT64 ConnectNonce;
    char PrincipalName[LOS_CAPABILITIES_PRINCIPAL_NAME_LENGTH];
    char SourceServiceName[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
    char SourceEndpointName[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
    char TargetServiceName[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
} LOS_CAPABILITIES_TRANSPORT_CONNECT_REQUEST;

typedef struct
{
    UINT32 Version;
    UINT32 Status;
    UINT32 ServiceClass;
    UINT32 TransportState;
    UINT32 EndpointClass;
    UINT32 SecurityMode;
    UINT64 Generation;
    UINT64 SessionId;
    UINT64 ServerNonce;
    LOS_CAPABILITIES_ENDPOINT_IDENTITY LocalIdentity;
    LOS_CAPABILITIES_ENDPOINT_IDENTITY RemoteIdentity;
} LOS_CAPABILITIES_TRANSPORT_CONNECT_RESULT;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 Reserved0;
    UINT32 EndpointClass;
    UINT32 SecurityMode;
    UINT64 Generation;
    UINT64 SessionId;
    UINT64 NextRequestSequence;
    UINT64 LastResponseSequence;
    UINT64 RequestAuthKey[2];
    UINT64 ResponseAuthKey[2];
    UINT64 RequestCipherKey[2];
    UINT64 ResponseCipherKey[2];
    LOS_CAPABILITIES_ENDPOINT_IDENTITY LocalIdentity;
    LOS_CAPABILITIES_ENDPOINT_IDENTITY RemoteIdentity;
    const LOS_CAPABILITIES_ENDPOINT_OBJECT *RequestEndpoint;
    const LOS_CAPABILITIES_ENDPOINT_OBJECT *ResponseEndpoint;
    LOS_CAPABILITIES_REQUEST_MAILBOX *RequestMailbox;
    LOS_CAPABILITIES_RESPONSE_MAILBOX *ResponseMailbox;
} LOS_CAPABILITIES_TRANSPORT_BINDING;

typedef struct
{
    UINT32 Version;
    UINT32 MutationType;
    UINT32 PrincipalType;
    UINT32 CapabilityClass;
    UINT32 Flags;
    UINT32 AuthoriserType;
    UINT32 Reserved0;
    UINT32 Reserved1;
    UINT64 PrincipalId;
    UINT64 GrantId;
    UINT64 ParentGrantId;
    UINT64 TimestampUtc;
    UINT64 EffectiveFromUtc;
    UINT64 EffectiveUntilUtc;
    char PrincipalName[LOS_CAPABILITIES_PRINCIPAL_NAME_LENGTH];
    char Namespace[LOS_CAPABILITIES_SERVICE_NAMESPACE_LENGTH];
    char Name[LOS_CAPABILITIES_SERVICE_NAME_LENGTH];
    char AuthoriserName[LOS_CAPABILITIES_AUTHORISER_NAME_LENGTH];
} LOS_CAPABILITIES_MUTATION_REQUEST;

typedef struct
{
    UINT32 Version;
    UINT32 Status;
    UINT32 State;
    UINT32 Reserved;
    UINT64 GrantId;
    UINT64 EventId;
} LOS_CAPABILITIES_MUTATION_RESULT;

#endif
