/*
 * File Name: InitCommandAbi.h
 * File Version: 0.3.19
 * Author: OpenAI
 * Email: dave66samaa@gmail.com
 * Creation Timestamp: 2026-04-07T11:02:18Z
 * Last Update Timestamp: 2026-04-08T09:30:00Z
 * Operating System Name: Liberation OS
 * Purpose: Declares shared interfaces and data structures for Liberation OS.
 */

#ifndef LOS_PUBLIC_INIT_COMMAND_ABI_H
#define LOS_PUBLIC_INIT_COMMAND_ABI_H

#include "Efi.h"
#include "CapabilitiesServiceAbi.h"
#include "SecureEndpointAbi.h"

#define LOS_INIT_COMMAND_VERSION 15U
#define LOS_INIT_COMMAND_FLAG_VERBOSE 0x00000001U

#define LOS_INIT_COMMAND_ENDPOINT_SEND 1U
#define LOS_INIT_COMMAND_ENDPOINT_RECEIVE 2U
#define LOS_INIT_COMMAND_ENDPOINT_SEND_EVENT 3U
#define LOS_INIT_COMMAND_ENDPOINT_RECEIVE_EVENT 4U

#define LOS_INIT_COMMAND_ENDPOINT_MASK_SEND (1ULL << 0)
#define LOS_INIT_COMMAND_ENDPOINT_MASK_RECEIVE (1ULL << 1)
#define LOS_INIT_COMMAND_ENDPOINT_MASK_SEND_EVENT (1ULL << 2)
#define LOS_INIT_COMMAND_ENDPOINT_MASK_RECEIVE_EVENT (1ULL << 3)
#define LOS_INIT_COMMAND_ENDPOINT_MASK_ALL     (LOS_INIT_COMMAND_ENDPOINT_MASK_SEND |      LOS_INIT_COMMAND_ENDPOINT_MASK_RECEIVE |      LOS_INIT_COMMAND_ENDPOINT_MASK_SEND_EVENT |      LOS_INIT_COMMAND_ENDPOINT_MASK_RECEIVE_EVENT)

#define LOS_INIT_COMMAND_MESSAGE_KIND_BOOTSTRAP_HELLO 1U
#define LOS_INIT_COMMAND_MESSAGE_KIND_BOOTSTRAP_RESPONSE 2U
#define LOS_INIT_COMMAND_MESSAGE_KIND_BOOTSTRAP_EVENT 3U

#define LOS_INIT_COMMAND_EVENT_BOOTSTRAP_START 1U
#define LOS_INIT_COMMAND_EVENT_BOOTSTRAP_COMPLETE 2U
#define LOS_INIT_COMMAND_EVENT_SERVICE_LOAD_REQUEST 3U
#define LOS_INIT_COMMAND_EVENT_SERVICE_LOAD_COMPLETE 4U
#define LOS_INIT_COMMAND_EVENT_SERVICE_IMAGE_VALIDATED 5U
#define LOS_INIT_COMMAND_EVENT_SERVICE_ENTRY_TRANSFER 6U
#define LOS_INIT_COMMAND_EVENT_SERVICE_ONLINE 7U
#define LOS_INIT_COMMAND_EVENT_SERVICE_STATE_READY 8U
#define LOS_INIT_COMMAND_EVENT_SERVICE_ACCESS_GRANTED 9U
#define LOS_INIT_COMMAND_EVENT_SERVICE_ACCESS_DENIED 10U

#define LOS_INIT_COMMAND_STATUS_SUCCESS 0U
#define LOS_INIT_COMMAND_STATUS_UNSUPPORTED 1U
#define LOS_INIT_COMMAND_STATUS_INVALID_CONTEXT 2U
#define LOS_INIT_COMMAND_STATUS_BAD_ENDPOINT 3U
#define LOS_INIT_COMMAND_STATUS_BAD_RESPONSE 4U
#define LOS_INIT_COMMAND_STATUS_TRANSPORT_FAILED 5U
#define LOS_INIT_COMMAND_STATUS_BAD_EVENT 6U
#define LOS_INIT_COMMAND_STATUS_BAD_SERVICE_COMMAND 7U
#define LOS_INIT_COMMAND_STATUS_BAD_SERVICE_IMAGE 8U
#define LOS_INIT_COMMAND_STATUS_SERVICE_LAUNCH_FAILED 9U
#define LOS_INIT_COMMAND_STATUS_BAD_SECURE_CHANNEL 10U
#define LOS_INIT_COMMAND_STATUS_SERVICE_NOT_ONLINE 11U
#define LOS_INIT_COMMAND_STATUS_ACCESS_DENIED 12U

#define LOS_INIT_COMMAND_BOOTSTRAP_TAG 0x54494E492D4C4F53ULL
#define LOS_INIT_COMMAND_BOOTSTRAP_SEQUENCE 1ULL
#define LOS_INIT_COMMAND_NAME_LENGTH 16U
#define LOS_INIT_COMMAND_SERVICE_PATH_LENGTH 96U

#define LOS_INIT_COMMAND_SERVICE_ACTION_NONE 0U
#define LOS_INIT_COMMAND_SERVICE_ACTION_LOAD_AND_RUN 1U

#define LOS_INIT_COMMAND_SERVICE_FLAG_WAIT_UNTIL_ONLINE 0x00000001U
#define LOS_INIT_COMMAND_SERVICE_FLAG_CAPABILITIES_IMPORT_REQUIRED 0x00000002U
#define LOS_INIT_COMMAND_SERVICE_FLAG_BOOTSTRAP_IMAGE_EMBEDDED 0x00000004U

#define LOS_INIT_COMMAND_SERVICE_IMAGE_SIGNATURE 0x474D4956534F4CULL
#define LOS_INIT_COMMAND_SERVICE_IMAGE_FORMAT_NONE 0U
#define LOS_INIT_COMMAND_SERVICE_IMAGE_FORMAT_ELF64 1U

typedef struct
{
    UINT32 Kind;
    UINT32 Flags;
    UINT64 EndpointId;
    UINT64 MailboxAddress;
    UINT64 MailboxSize;
} LOS_INIT_COMMAND_ENDPOINT;

typedef struct
{
    UINT32 Version;
    UINT32 ImageFormat;
    UINT32 Flags;
    UINT32 Reserved0;
    UINT64 Signature;
    UINT64 RequestId;
    UINT64 ImageAddress;
    UINT64 ImageSize;
    UINT64 EntryVirtualAddress;
    UINT64 BootstrapCallableEntryAddress;
    UINT64 BootstrapContextAddress;
    UINT64 BootstrapContextSize;
    UINT64 BootstrapStateAddress;
    UINT64 BootstrapStateSize;
    char ServicePath[LOS_INIT_COMMAND_SERVICE_PATH_LENGTH];
} LOS_INIT_COMMAND_SERVICE_IMAGE;

typedef struct
{
    UINT32 Action;
    UINT32 Flags;
    UINT64 RequestId;
    char ServicePath[LOS_INIT_COMMAND_SERVICE_PATH_LENGTH];
    LOS_INIT_COMMAND_SERVICE_IMAGE ServiceImage;
    LOS_SECURE_ENDPOINT_POLICY SecureChannelPolicy;
} LOS_INIT_COMMAND_SERVICE_REQUEST;

typedef struct
{
    UINT32 Version;
    UINT32 Flags;
    LOS_INIT_COMMAND_ENDPOINT Send;
    LOS_INIT_COMMAND_ENDPOINT Receive;
    LOS_INIT_COMMAND_ENDPOINT SendEvent;
    LOS_INIT_COMMAND_ENDPOINT ReceiveEvent;
    LOS_INIT_COMMAND_SERVICE_REQUEST ServiceRequest;
    LOS_CAPABILITIES_BOOTSTRAP_CONTEXT Capabilities;
} LOS_INIT_COMMAND_CONTEXT;

typedef struct
{
    UINT32 Version;
    UINT32 Kind;
    UINT32 HeaderBytes;
    UINT32 Flags;
    UINT64 RequestTag;
    UINT64 RequestValue;
    UINT64 Sequence;
    UINT64 EndpointMask;
    UINT64 SenderEndpointId;
    UINT64 ReceiveEndpointId;
    UINT64 SendEventEndpointId;
    UINT64 ReceiveEventEndpointId;
    char CommandName[LOS_INIT_COMMAND_NAME_LENGTH];
} LOS_INIT_COMMAND_MESSAGE;

typedef struct
{
    UINT32 Version;
    UINT32 Status;
    UINT32 HeaderBytes;
    UINT32 Reserved;
    UINT64 ResponseTag;
    UINT64 ResponseValue;
    UINT64 AcceptedEndpointMask;
    UINT64 Sequence;
    UINT64 SenderEndpointId;
    UINT64 ReceiverEndpointId;
} LOS_INIT_COMMAND_RESPONSE;

typedef struct
{
    UINT32 Version;
    UINT32 Kind;
    UINT32 HeaderBytes;
    UINT32 Reserved;
    UINT64 EventCode;
    UINT64 EventValue;
    UINT64 Sequence;
    UINT64 SenderEndpointId;
    UINT64 ReceiverEndpointId;
} LOS_INIT_COMMAND_EVENT_RECORD;

#endif
