#ifndef LOS_MEMORY_MANAGER_SERVICE_ABI_H
#define LOS_MEMORY_MANAGER_SERVICE_ABI_H

#include "Efi.h"
#include "VirtualMemory.h"

#define LOS_MEMORY_MANAGER_BOOTSTRAP_VERSION 10U
#define LOS_MEMORY_MANAGER_SERVICE_PATH_CHARACTERS 128U
#define LOS_MEMORY_MANAGER_SERVICE_NAME "MemoryManager"

#define LOS_MEMORY_MANAGER_ENDPOINT_KERNEL_TO_SERVICE 0x4D4D535256000001ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_SERVICE_TO_KERNEL 0x4D4D535256000002ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_SERVICE_EVENTS 0x4D4D535256000003ULL

#define LOS_MEMORY_MANAGER_ENDPOINT_ROLE_RECEIVE 1U
#define LOS_MEMORY_MANAGER_ENDPOINT_ROLE_REPLY 2U
#define LOS_MEMORY_MANAGER_ENDPOINT_ROLE_EVENT 3U

#define LOS_MEMORY_MANAGER_ENDPOINT_STATE_OFFLINE 0U
#define LOS_MEMORY_MANAGER_ENDPOINT_STATE_DEFINED 1U
#define LOS_MEMORY_MANAGER_ENDPOINT_STATE_READY 2U
#define LOS_MEMORY_MANAGER_ENDPOINT_STATE_BOUND 3U
#define LOS_MEMORY_MANAGER_ENDPOINT_STATE_ONLINE 4U

#define LOS_MEMORY_MANAGER_ENDPOINT_FLAG_KERNEL_OWNED 0x0000000000000001ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_FLAG_BOOTSTRAP_OBJECT 0x0000000000000002ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_FLAG_MAILBOX_ATTACHED 0x0000000000000004ULL
#define LOS_MEMORY_MANAGER_ENDPOINT_FLAG_SERVICE_VISIBLE 0x0000000000000008ULL

#define LOS_MEMORY_MANAGER_OPERATION_BOOTSTRAP_ATTACH 1U
#define LOS_MEMORY_MANAGER_OPERATION_QUERY_MEMORY_REGIONS 2U
#define LOS_MEMORY_MANAGER_OPERATION_RESERVE_FRAMES 3U
#define LOS_MEMORY_MANAGER_OPERATION_CLAIM_FRAMES 4U
#define LOS_MEMORY_MANAGER_OPERATION_MAP_PAGES 5U
#define LOS_MEMORY_MANAGER_OPERATION_UNMAP_PAGES 6U

#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_READY 0U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_ALREADY_ATTACHED 1U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_INVALID_REQUEST 2U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_VERSION_MISMATCH 3U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_LAUNCH_BLOCK_MISMATCH 4U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_ENDPOINT_MISMATCH 5U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_MAILBOX_MISMATCH 6U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_SERVICE_ROOT_MISMATCH 7U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_SERVICE_IMAGE_MISMATCH 8U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_SERVICE_STATE_INVALID 9U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_OPERATION_SET_INVALID 10U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_ENTRY_MISMATCH 11U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT_STACK_TOP_MISMATCH 12U

#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_OFFLINE 0U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_DEFINED 1U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_LAUNCHED 2U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_STAGED 3U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_IMAGE_READY 4U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_READY 5U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_SERVICE_PREPARED 6U
#define LOS_MEMORY_MANAGER_BOOTSTRAP_STATE_SERVICE_ONLINE 7U

#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_KERNEL_LOW_LEVEL_FRAMES 0x0000000000000001ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_KERNEL_LOW_LEVEL_PAGING 0x0000000000000002ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_ENDPOINT_BRIDGE 0x0000000000000004ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_PROBE_COMPLETE 0x0000000000000008ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_TRANSPORT_READY 0x0000000000000010ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_LAUNCH_BLOCK_READY 0x0000000000000020ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_STACK_READY 0x0000000000000040ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_IMAGE_READY 0x0000000000000080ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_ENTRY_PUBLISHED 0x0000000000000100ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_LAUNCH_PREPARED 0x0000000000000200ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_ONLINE 0x0000000000000400ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_ISOLATED_ROOT_READY 0x0000000000000800ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_SERVICE_CONTEXT_SWITCHED 0x0000000000001000ULL
#define LOS_MEMORY_MANAGER_BOOTSTRAP_FLAG_ATTACH_COMPLETE 0x0000000000008000ULL

#define LOS_MEMORY_MANAGER_ENDPOINT_OBJECT_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_OBJECT_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_TASK_OBJECT_PAGE_COUNT 1U

#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_STATE_OFFLINE 0U
#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_STATE_DEFINED 1U
#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_STATE_READY 2U
#define LOS_MEMORY_MANAGER_ADDRESS_SPACE_STATE_ACTIVE 3U

#define LOS_MEMORY_MANAGER_TASK_STATE_OFFLINE 0U
#define LOS_MEMORY_MANAGER_TASK_STATE_DEFINED 1U
#define LOS_MEMORY_MANAGER_TASK_STATE_READY 2U
#define LOS_MEMORY_MANAGER_TASK_STATE_LAUNCHED 3U
#define LOS_MEMORY_MANAGER_TASK_STATE_RUNNING 4U
#define LOS_MEMORY_MANAGER_TASK_STATE_ONLINE 5U

#define LOS_MEMORY_MANAGER_TASK_FLAG_BOOTSTRAP_HOSTED 0x0000000000000001ULL
#define LOS_MEMORY_MANAGER_TASK_FLAG_FIRST_USER_TASK 0x0000000000000002ULL
#define LOS_MEMORY_MANAGER_TASK_FLAG_SERVICE_READY 0x0000000000000004ULL

#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_FREE 0U
#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_READY 1U
#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_COMPLETE 2U

#define LOS_MEMORY_MANAGER_EVENT_SERVICE_ONLINE 1U
#define LOS_MEMORY_MANAGER_EVENT_SERVICE_READY_FOR_REQUESTS 2U
#define LOS_MEMORY_MANAGER_EVENT_SERVICE_FAULT 3U

#define LOS_MEMORY_MANAGER_REQUEST_MAILBOX_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_RESPONSE_MAILBOX_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_EVENT_MAILBOX_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_LAUNCH_BLOCK_PAGE_COUNT 1U
#define LOS_MEMORY_MANAGER_SERVICE_STACK_PAGE_COUNT 8U
#define LOS_MEMORY_MANAGER_MAILBOX_SLOT_COUNT 8U

#define LOS_MEMORY_MANAGER_BOOTSTRAP_SIGNATURE 0x5450424D4D534F4CULL
#define LOS_MEMORY_MANAGER_MAILBOX_SIGNATURE 0x58424D4D4D534F4CULL
#define LOS_MEMORY_MANAGER_LAUNCH_BLOCK_SIGNATURE 0x4B4C424D4D534F4CULL

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 Role;
    UINT32 State;
    UINT32 Reserved0;
    UINT64 Flags;
    UINT64 EndpointId;
    UINT64 MailboxPhysicalAddress;
    UINT64 MailboxSize;
    UINT64 PeerEndpointId;
} LOS_MEMORY_MANAGER_ENDPOINT_OBJECT;

typedef struct
{
    UINT64 KernelToService;
    UINT64 ServiceToKernel;
    UINT64 ServiceEvents;
} LOS_MEMORY_MANAGER_ENDPOINT_SET;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 State;
    UINT64 Flags;
    UINT64 RootTablePhysicalAddress;
    UINT64 KernelRootTablePhysicalAddress;
    UINT64 DirectMapBase;
    UINT64 DirectMapSize;
    UINT64 ServiceImagePhysicalAddress;
} LOS_MEMORY_MANAGER_ADDRESS_SPACE_OBJECT;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 State;
    UINT64 Flags;
    UINT64 TaskId;
    UINT64 AddressSpaceObjectPhysicalAddress;
    UINT64 EntryVirtualAddress;
    UINT64 StackTopPhysicalAddress;
    UINT64 StackTopVirtualAddress;
    UINT64 LastRequestId;
    UINT64 Heartbeat;
} LOS_MEMORY_MANAGER_TASK_OBJECT;

typedef struct
{
    UINT32 Version;
    UINT32 Reserved;
    UINT64 LaunchBlockPhysicalAddress;
    UINT64 OfferedOperations;
    UINT64 BootstrapFlags;
    UINT64 KernelToServiceEndpointId;
    UINT64 ServiceToKernelEndpointId;
    UINT64 ServiceEventsEndpointId;
    UINT64 RequestMailboxPhysicalAddress;
    UINT64 ResponseMailboxPhysicalAddress;
    UINT64 EventMailboxPhysicalAddress;
    UINT64 MemoryRegionTablePhysicalAddress;
    UINT64 MemoryRegionCount;
    UINT64 MemoryRegionEntrySize;
    UINT64 ServicePageMapLevel4PhysicalAddress;
    UINT64 ServiceImagePhysicalAddress;
    UINT64 ServiceImageSize;
    UINT64 ServiceEntryVirtualAddress;
    UINT64 ServiceStackTopVirtualAddress;
} LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_REQUEST;

typedef struct
{
    UINT32 BootstrapResult;
    UINT32 BootstrapState;
    UINT64 NegotiatedOperations;
    UINT64 BootstrapFlags;
    UINT64 ActiveRootTablePhysicalAddress;
    UINT64 KernelRootTablePhysicalAddress;
    UINT64 ServiceHeartbeat;
    UINT64 LastProcessedRequestId;
} LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT;

typedef struct
{
    UINT32 Operation;
    UINT32 Reserved0;
    UINT64 RequestId;
    union
    {
        LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_REQUEST BootstrapAttach;
        struct
        {
            LOS_X64_MEMORY_REGION *Buffer;
            UINTN BufferRegionCapacity;
        } QueryMemoryRegions;
        LOS_X64_RESERVE_FRAMES_REQUEST ReserveFrames;
        LOS_X64_CLAIM_FRAMES_REQUEST ClaimFrames;
        LOS_X64_MAP_PAGES_REQUEST MapPages;
        LOS_X64_UNMAP_PAGES_REQUEST UnmapPages;
    } Payload;
} LOS_MEMORY_MANAGER_REQUEST_MESSAGE;

typedef struct
{
    UINT32 Operation;
    UINT32 Status;
    UINT64 RequestId;
    union
    {
        LOS_MEMORY_MANAGER_BOOTSTRAP_ATTACH_RESULT BootstrapAttach;
        LOS_X64_QUERY_MEMORY_REGIONS_RESULT QueryMemoryRegions;
        LOS_X64_RESERVE_FRAMES_RESULT ReserveFrames;
        LOS_X64_CLAIM_FRAMES_RESULT ClaimFrames;
        LOS_X64_MAP_PAGES_RESULT MapPages;
        LOS_X64_UNMAP_PAGES_RESULT UnmapPages;
    } Payload;
} LOS_MEMORY_MANAGER_RESPONSE_MESSAGE;

typedef struct
{
    UINT32 EventType;
    UINT32 Status;
    UINT64 Sequence;
    UINT64 Value0;
    UINT64 Value1;
} LOS_MEMORY_MANAGER_EVENT_MESSAGE;

typedef struct
{
    UINT32 SlotState;
    UINT32 Reserved;
    UINT64 Sequence;
    LOS_MEMORY_MANAGER_REQUEST_MESSAGE Message;
} LOS_MEMORY_MANAGER_REQUEST_SLOT;

typedef struct
{
    UINT32 SlotState;
    UINT32 Reserved;
    UINT64 Sequence;
    LOS_MEMORY_MANAGER_RESPONSE_MESSAGE Message;
} LOS_MEMORY_MANAGER_RESPONSE_SLOT;

typedef struct
{
    UINT32 SlotState;
    UINT32 Reserved;
    UINT64 Sequence;
    LOS_MEMORY_MANAGER_EVENT_MESSAGE Message;
} LOS_MEMORY_MANAGER_EVENT_SLOT;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 Reserved;
    UINT64 EndpointId;
    UINT64 SlotCount;
    UINT64 ProduceIndex;
    UINT64 ConsumeIndex;
} LOS_MEMORY_MANAGER_MAILBOX_HEADER;

typedef struct
{
    LOS_MEMORY_MANAGER_MAILBOX_HEADER Header;
    LOS_MEMORY_MANAGER_REQUEST_SLOT Slots[LOS_MEMORY_MANAGER_MAILBOX_SLOT_COUNT];
} LOS_MEMORY_MANAGER_REQUEST_MAILBOX;

typedef struct
{
    LOS_MEMORY_MANAGER_MAILBOX_HEADER Header;
    LOS_MEMORY_MANAGER_RESPONSE_SLOT Slots[LOS_MEMORY_MANAGER_MAILBOX_SLOT_COUNT];
} LOS_MEMORY_MANAGER_RESPONSE_MAILBOX;

typedef struct
{
    LOS_MEMORY_MANAGER_MAILBOX_HEADER Header;
    LOS_MEMORY_MANAGER_EVENT_SLOT Slots[LOS_MEMORY_MANAGER_MAILBOX_SLOT_COUNT];
} LOS_MEMORY_MANAGER_EVENT_MAILBOX;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 State;
    UINT64 Flags;
    LOS_MEMORY_MANAGER_ENDPOINT_SET Endpoints;
    UINT64 KernelToServiceEndpointObjectPhysicalAddress;
    UINT64 ServiceToKernelEndpointObjectPhysicalAddress;
    UINT64 ServiceEventsEndpointObjectPhysicalAddress;
    UINT64 ServiceAddressSpaceObjectPhysicalAddress;
    UINT64 ServiceTaskObjectPhysicalAddress;
    UINT64 ServicePageMapLevel4PhysicalAddress;
    UINT64 MemoryRegionTablePhysicalAddress;
    UINT64 MemoryRegionCount;
    UINT64 MemoryRegionEntrySize;
    UINT64 SupportedOperations;
    UINT64 ServiceImagePhysicalAddress;
    UINT64 ServiceImageSize;
    UINT64 ServiceEntryVirtualAddress;
    UINT64 ServiceStackPhysicalAddress;
    UINT64 ServiceStackPageCount;
    UINT64 RequestMailboxPhysicalAddress;
    UINT64 RequestMailboxSize;
    UINT64 ResponseMailboxPhysicalAddress;
    UINT64 ResponseMailboxSize;
    UINT64 EventMailboxPhysicalAddress;
    UINT64 EventMailboxSize;
    UINT64 LaunchBlockPhysicalAddress;
    UINT64 LaunchBlockSize;
    CHAR16 ServicePath[LOS_MEMORY_MANAGER_SERVICE_PATH_CHARACTERS];
} LOS_MEMORY_MANAGER_BOOTSTRAP_INFO;

typedef struct
{
    UINT64 Signature;
    UINT32 Version;
    UINT32 State;
    UINT64 Flags;
    LOS_MEMORY_MANAGER_ENDPOINT_SET Endpoints;
    UINT64 KernelToServiceEndpointObjectPhysicalAddress;
    UINT64 ServiceToKernelEndpointObjectPhysicalAddress;
    UINT64 ServiceEventsEndpointObjectPhysicalAddress;
    UINT64 ServiceAddressSpaceObjectPhysicalAddress;
    UINT64 ServiceTaskObjectPhysicalAddress;
    UINT64 ServicePageMapLevel4PhysicalAddress;
    UINT64 MemoryRegionTablePhysicalAddress;
    UINT64 MemoryRegionCount;
    UINT64 MemoryRegionEntrySize;
    UINT64 RequestMailboxPhysicalAddress;
    UINT64 RequestMailboxSize;
    UINT64 ResponseMailboxPhysicalAddress;
    UINT64 ResponseMailboxSize;
    UINT64 EventMailboxPhysicalAddress;
    UINT64 EventMailboxSize;
    UINT64 LaunchBlockPhysicalAddress;
    UINT64 ServiceStackPhysicalAddress;
    UINT64 ServiceStackPageCount;
    UINT64 ServiceStackTopPhysicalAddress;
    UINT64 ServiceStackTopVirtualAddress;
    UINT64 ServiceImagePhysicalAddress;
    UINT64 ServiceImageSize;
    UINT64 ServiceEntryVirtualAddress;
    CHAR16 ServicePath[LOS_MEMORY_MANAGER_SERVICE_PATH_CHARACTERS];
} LOS_MEMORY_MANAGER_LAUNCH_BLOCK;

#endif
