/*
 * File Name: SecureEndpointAbi.h
 * File Version: 0.3.15
 * Author: OpenAI
 * Email: dave66samaa@gmail.com
 * Creation Timestamp: 2026-04-07T14:35:00Z
 * Last Update Timestamp: 2026-04-09T19:40:00Z
 * Operating System Name: Liberation OS
 * Purpose: Declares secure endpoint session and message structures for Liberation OS.
 */

#ifndef LOS_PUBLIC_SECURE_ENDPOINT_ABI_H
#define LOS_PUBLIC_SECURE_ENDPOINT_ABI_H

#include "Efi.h"

#define LOS_SECURE_ENDPOINT_VERSION 1U
#define LOS_SECURE_ENDPOINT_KEY_NAME_LENGTH 32U
#define LOS_SECURE_ENDPOINT_NONCE_BYTES 24U
#define LOS_SECURE_ENDPOINT_TAG_BYTES 16U

#define LOS_SECURE_ENDPOINT_MODE_PLAINTEXT 0U
#define LOS_SECURE_ENDPOINT_MODE_AUTHENTICATED 1U
#define LOS_SECURE_ENDPOINT_MODE_ENCRYPTED 2U
#define LOS_SECURE_ENDPOINT_MODE_ENCRYPTED_MUTUAL 3U

#define LOS_SECURE_ENDPOINT_KEY_EXCHANGE_NONE 0U
#define LOS_SECURE_ENDPOINT_KEY_EXCHANGE_BOOTSTRAP_PUBLIC_KEY 1U
#define LOS_SECURE_ENDPOINT_KEY_EXCHANGE_SESSION_DERIVATION 2U

#define LOS_SECURE_ENDPOINT_FLAG_REQUIRED 0x00000001U
#define LOS_SECURE_ENDPOINT_FLAG_MUTUAL_AUTH_REQUIRED 0x00000002U
#define LOS_SECURE_ENDPOINT_FLAG_REPLAY_PROTECTION 0x00000004U
#define LOS_SECURE_ENDPOINT_FLAG_ALLOW_BOOTSTRAP_PLAINTEXT 0x00000008U
#define LOS_SECURE_ENDPOINT_FLAG_PAYLOAD_ENCRYPTED 0x00000010U
#define LOS_SECURE_ENDPOINT_FLAG_PAYLOAD_AUTHENTICATED 0x00000020U

#define LOS_SECURE_ENDPOINT_STATUS_SUCCESS 0U
#define LOS_SECURE_ENDPOINT_STATUS_UNSUPPORTED 1U
#define LOS_SECURE_ENDPOINT_STATUS_INVALID_PARAMETER 2U
#define LOS_SECURE_ENDPOINT_STATUS_HANDSHAKE_REQUIRED 3U
#define LOS_SECURE_ENDPOINT_STATUS_KEY_UNAVAILABLE 4U
#define LOS_SECURE_ENDPOINT_STATUS_REPLAY_DETECTED 5U
#define LOS_SECURE_ENDPOINT_STATUS_AUTHENTICATION_FAILED 6U

#define LOS_SECURE_ENDPOINT_MESSAGE_KIND_HANDSHAKE_HELLO 1U
#define LOS_SECURE_ENDPOINT_MESSAGE_KIND_HANDSHAKE_ACCEPT 2U
#define LOS_SECURE_ENDPOINT_MESSAGE_KIND_SESSION_DATA 3U
#define LOS_SECURE_ENDPOINT_MESSAGE_KIND_SESSION_EVENT 4U

typedef struct
{
    UINT32 Version;
    UINT32 Mode;
    UINT32 KeyExchange;
    UINT32 Flags;
    UINT64 EndpointId;
    UINT64 KeyId;
    char KeyName[LOS_SECURE_ENDPOINT_KEY_NAME_LENGTH];
} LOS_SECURE_ENDPOINT_POLICY;

typedef struct
{
    UINT32 Version;
    UINT32 Flags;
    UINT64 SessionId;
    UINT64 LocalPrincipalId;
    UINT64 RemotePrincipalId;
    UINT64 SendSequence;
    UINT64 ReceiveSequence;
    LOS_SECURE_ENDPOINT_POLICY Policy;
} LOS_SECURE_ENDPOINT_SESSION;

typedef struct
{
    UINT32 Version;
    UINT32 Kind;
    UINT32 HeaderBytes;
    UINT32 Flags;
    UINT64 SessionId;
    UINT64 Sequence;
    UINT64 SenderEndpointId;
    UINT64 ReceiverEndpointId;
    UINT8 Nonce[LOS_SECURE_ENDPOINT_NONCE_BYTES];
    UINT8 Tag[LOS_SECURE_ENDPOINT_TAG_BYTES];
} LOS_SECURE_ENDPOINT_MESSAGE_HEADER;

#endif
